### ISSUE TITLE
Extend placeholder with a variable and hyphen break sass-lint

### ISSUE THREAD

**Issue by sound-matt** [sasstools/sass-lint#1027]
What version of Sass Lint are you using? 
1.10.2

Please include any relevant parts of your configuration
Ubuntu 16.10

What did you do? Please include the actual source code causing the issue.
`@extend %#{$foo}--modifier;`
Put hyphen after the variable seens to break sass-lint

What actually happened? Please include any error messages given to you by Sass Lint.
`error  Please check validity of the block starting from line #136  Fatal`

If you're using a IDE plugin have you tried the CLI too? 
yes

**Comment by DanPurdy** [comment]
This is a problem with the AST we use. It looks to be fixed in the latest version of Gonzales-pe but we haven't had the time to update yet, we believe there are also a few regressions we need to check for.

**Comment by bgriffith** [comment]
This is fixed in the newly released version v1.11.0. Please let me know if you still have issues. Thanks!
