### ISSUE TITLE
Feature request: autofix

### ISSUE THREAD

**Issue by graingert** [sasstools/sass-lint#1031]
Simple rules, like indentation, hex-notation etc. Should be easy to autofix

**Comment by chrisjeffery** [comment]
Does the parser support tree modifications and rewriting the sass files from the tree? If not, it's not easy.

**Comment by DanPurdy** [comment]
It does support it, and there's already an open PR with some of the work done but unfortunately the author has repeatedly ignored our feedback and requests on how to implement so we've never taken the time to review it properly. If you'd like to take over and work on it please feel free..

**Comment by graingert** [comment]
What's the PR number?


On 10 Apr 2017 15:25, "Dan Purdy" <notifications@github.com> wrote:

It does support it, and there's already an open PR with some of the work
done but unfortunately the author has repeatedly ignored our feedback and
requests on how to implement so we've never taken the time to review it
properly. If you'd like to take over and work on it please feel free..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sasstools/sass-lint/issues/1031#issuecomment-292965377>,
or mute the thread

**Comment by chrisjeffery** [comment]
looks like this one
https://github.com/sasstools/sass-lint/pull/997

**Comment by DanPurdy** [comment]
Also see #778 and #728

**Comment by srowhani** [comment]
If this is something you guys need I can put more time into it. I've since addressed the comments mentioned.

**Comment by graingert** [comment]
@DanPurdy closing as dupe in favor of #904

**Comment by stephanebruckert** [comment]
New repo just for this https://github.com/srowhani/sass-lint-auto-fix
