### ISSUE TITLE
Doesn't work with Node v7.7

### ISSUE THREAD

**Issue by TejasQ** [sasstools/sass-lint#1034]
What version of Sass Lint are you using?
^1.10.2

What did you do? Please include the actual source code causing the issue.
`sass-lint -v -q`
I had a .sass-lint.yml file in my root.

What did you expect to happen?
It should have linted stuff.

What actually happened? Please include any error messages given to you by Sass Lint.
Module `globule` not found.
I then did `npm install globule -D`, and then it threw `module "commander" not found`.
I installed commander, but it would not see it. Like ever.

If you're using a IDE plugin have you tried the CLI too?
Yes. This is *only* about the CLI.

**Comment by DanPurdy** [comment]
I'm afraid there must be something else that's the problem here, works fine for me.

![screen shot 2017-03-11 at 16 16 09](https://cloud.githubusercontent.com/assets/1386054/23824840/2878728c-0676-11e7-9d75-8c0d6a465568.png)

try clearing everything and reinstall i guess?

**Comment by TejasQ** [comment]
After some digging, I found out it was because my `NODE_ENV` was `production`.
