### ISSUE TITLE
Pass arguments when using sass-lint via npm run

### ISSUE THREAD

**Issue by NitroBAY** [sasstools/sass-lint#1037]
Hello,
I'm trying to use the CLI cmd, as I really **hate** the idea of installing global-dependencies (so if you change your env you got to remember everything and reinstall everything...) I installed with `--save-dev`.
`node_modules\.bin\sass-lint -q` is working smoothly.
But the problem is that if I try to put `"sass-lint": "sass-lint"` in my `"scripts"` part of my `package.json` file so I can just `npm run sass-lint` then I cannot pass properly arguments. Indeed if I do `npm run sass-lint -- -q -v` everything is working perfectly (it throws errors and warning) but at the end it logs 
```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\My Name\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "sass-lint" "--" "-q" "-v"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 32-PHARMACIE-METEOR@ sass-lint: `sass-lint "-q" "-v"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 32-PHARMACIE-METEOR@ sass-lint script 'sass-lint "-q" "-v"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the 32-PHARMACIE-METEOR package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sass-lint "-q" "-v"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 32-PHARMACIE-METEOR
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 32-PHARMACIE-METEOR
npm ERR! There is likely additional logging output above.
```

**Comment by justinhough** [comment]
@NitroBAY For most of my projects I run the following command via NPM `npm run sass-test` and this runs `sass-lint -c .sass-lint.yml -v -q` from my package.json. You could likely put the full command in your package.json then it would work fine.

Example:
`"sass-lint": "sass-lint -- -q -v"`

**Comment by DanPurdy** [comment]
@NitroBAY I'm afraid @justinhough is correct, when you pass flags the way you are doing you're actually passing them to NPM instead of sass-lint. NPM doesn't proxy flags like that. Instead as suggested you need to put the full command in your NPM package scripts as a string.

> @NitroBAY For most of my projects I run the following command via NPM npm run sass-test and this runs sass-lint -c .sass-lint.yml -v -q from my package.json. You could likely put the full command in your package.json then it would work fine.

Example:
"sass-lint": "sass-lint -- -q -v"
