### ISSUE TITLE
A browser edition

### ISSUE THREAD

**Issue by blackmiaool** [sasstools/sass-lint#1056]
Recently I [forked](https://github.com/blackmiaool/sass-lint) this repo and make it run in browser ([Why](http://stackoverflow.com/questions/43127937/scss-linter-for-codemirror/43203069#43203069)). And I think the fork can be useful for others. What do you think about it?

BTW, this repo is really awesome!

[codemirror demo](http://blackmiaool.com/soa/43127937/cm.html)

[my fork](https://github.com/blackmiaool/sass-lint)

**Comment by DanPurdy** [comment]
Very cool. Nice work. Put a PR in to show it in our README if you'd like.
