### ISSUE TITLE
ESLint as dependency?

### ISSUE THREAD

**Issue by yangshun** [sasstools/sass-lint#1070]
I had a brief look at the source code, and don't find that `eslint` is being used in the source itself, seems like it's only being used for linting the source code and not as a utility library. May I know why it's listed under `dependencies` in `package.json`?

If it's just for linting the source code, it would be more appropriate to be under `devDependencies`. Putting an outdated `eslint` as dependency causes projects to not be able to upgrade to the latest `eslint` which is > `3.0.0` at the moment.

Would be happy to submit a PR to fix this if necessary. Please let me know (:

**Comment by DanPurdy** [comment]
We are using the eslint formatters directly in lieu of our own which is a shame but not had the time to get round to making our own. Also upgrading eslint means we'd need a major version bump too as we no longer would be supporting node versions < v4. We updated previously and had to roll back due to people stuck on build systems using old node versions.

Unfortunately this means it's correctly listed as a dependency but until I can find some time to work on this again we're stuck.

**Comment by yangshun** [comment]
Oh I see, thanks for the explanation. I searched the code base for `eslint` and only saw the use of the ESLint formatter in the test, not realizing it was being used [here](https://github.com/sasstools/sass-lint/blob/251361228772cf5f106877329c5420b95f518193/index.js#L257) as well.

What do you think of the following two approaches:
1. Major bump `sass-lint` and major bump `eslint` as well to use eslint@>3.00?
2. Copy out the `eslint` formatters into the `sass-lint` project.

**Comment by w3apps** [comment]
+1 The outdated eslint listed in "dependencies"  rather than "devDependencies" is a buzzkiller.

**Comment by john-kurkowski** [comment]
@yangshun why closed?

**Comment by DanPurdy** [comment]
Dont worry, we're going to drop a v2 soon to deprecate our support for older node versions and also drop our direct dependency on Eslint's formatters. Will be out in the next couple of days/weeks hopefully and then you wont have this issues at all. It was unfortunately necessary to include it in our dependencies as we used their formatters directly.

**Comment by john-kurkowski** [comment]
> we're going to drop a v2 soon to deprecate our support for older node versions and also drop our direct dependency on Eslint's formatters. Will be out in the next couple of days/weeks 

Is there another issue we can track for this issue's release? For tracking 2.0? #400 hasn't been updated in a while.

**Comment by IGx89** [comment]
Hi @DanPurdy ! It sounds like you were really close to a v2 release a year ago. Any chance of that happening before end of year?

**Comment by jimthedev** [comment]
@IGx89 did you ever end up hearing anything from @DanPurdy? This dep is a bummer.

**Comment by IGx89** [comment]
No, however @chancestrickland built v1.13 with this fix in November so it's close to release, however he hasn't released it yet either...

**Comment by jimthedev** [comment]
@IGx89 cool thanks.
