### ISSUE TITLE
Solve overidding of style sheets by multiple partners

### ISSUE THREAD

**Issue by subhroneeldey** [sasstools/sass-lint#1082]
In our website multiple partners make use of stylesheets and they create classes which sometimes have the same name and the styles get overwritten. So I wanted to enforce that each partner uses the class name prefixed by their name. For Example : class partner1_abc, class partner2_abc, class partner3_abc, etc. Now I want to enforce this using linting plugins or gulp tasks. I welcome anyone who could give me a valuable suggestion

**Comment by DanPurdy** [comment]
You should probably turn to stackOverflow for questions like this as we don't really have the capacity to help out as much as we'd like to when we're working on the project. But as a starter the below may help.

use the classname format rule [https://github.com/sasstools/sass-lint/blob/develop/docs/rules/class-name-format.md](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/class-name-format.md)

You can pass custom regex to it which in your example would be one of the contributors names i.e. `company1|company2` followed by regex for the rest of the classname if you wish. Make sure the regex checks for the company name string at the beginning of the file. You can use the custom convention explanation to provide a decent error message to your partners to say what they need to do. Using the standard gulp-sass-lint plugin with this rule setup in the config file that you pass to all your partners to use and you'd be able to enforce this fairly easily.

Hope that helps.

**Comment by subhroneeldey** [comment]
I have solved the issue bur still thanks for the reply. I know it is
difficult to reply when working in such a large project
