### ISSUE TITLE
[sass|scss] css variable don't work

### ISSUE THREAD

**Issue by hopefuture** [sasstools/sass-lint#1098]
When I use css variable to write style. There is a error tooltip: "Please check validity of the block starting from line "

example 

```
:root {
  --theme-color: #346789;
}
```

**Comment by eugef** [comment]
Any update on supporting css variables?

**Comment by bgriffith** [comment]
Going to close as this is a duplicate of https://github.com/sasstools/sass-lint/issues/877

A fix is on the way.
