### ISSUE TITLE
When's the next release?

### ISSUE THREAD

**Issue by OriR** [sasstools/sass-lint#1109]
The latest release is from Nov 9, 2016 which is almost a year old.
Are there any plans for making a new release anytime soon? I've been looking forward for #1106 since I'm using `grid-gap`.

**Comment by DanPurdy** [comment]
Hopefully in the next day or so!

We've been pretty inactive for a while now due to other commitments but the last week or so we've been trying to revive things a bit..

**Comment by bgriffith** [comment]
`v.1.11.0` just published to npm
