### ISSUE TITLE
no-color-keywords flags CSS variables

### ISSUE THREAD

**Issue by inukshuk** [sasstools/sass-lint#1120]
What version of Sass Lint are you using?

1.11.1

What did you do? Please include the actual source code causing the issue.

`$badge-bg: var(--red);`

What did you expect to happen?

No errors reported.

What actually happened? Please include any error messages given to you by Sass Lint.

The line in question is flagged as "error  Color 'red' should be written in its hexadecimal form #ff0000  no-color-keywords"

**Comment by DanPurdy** [comment]
@inukshuk thanks for this, should of checked this when @bgriffith got css variables support into our parser. WIll look to fix soon 👍

**Comment by DanPurdy** [comment]
Released in 1.12.0
