### ISSUE TITLE
Unexpected parse error in file if I use CSS Custom Properties (CSS Variables)

### ISSUE THREAD

**Issue by barcia** [sasstools/sass-lint#1189]
When I try to use the CSS Custom Properties, the linter fails and show "Unexpected parse error in file" at first line.

<img width="1006" alt="captura de pantalla 2018-03-15 19 33 10" src="https://user-images.githubusercontent.com/5719646/37484232-44a6431e-2888-11e8-8f84-ec091755e53b.png">

I am using Atom, [linter](https://github.com/AtomLinter/Linter) and [linter-sass-lint](https://atom.io/packages/linter-sass-lint) 

How can I solve it?

**Comment by davidenke** [comment]
@barcia the problem comes from the property-sort-order rule, which expects the first part of a declaration block to be a `property`, not a `customProperty`.

Quick fix is to disable the property-sort-order rule.

**Comment by barcia** [comment]
Oh, thanks. This solve it. 👍
