### ISSUE TITLE
1.2 Cleanup

### ISSUE THREAD

**Issue by Snugug** [sasstools/sass-lint#123]
Go through all of everything and make sure everything is clean and consistent.

- [x] Options in rules documentation all formatted the same
- [x] Rules with no options all are in form of `no-{{rule}}`
- [x] All rule options are dasherized
- [x] All rules have documentation
- [x] Divide tests in to individual files

**Comment by DanPurdy** [comment]
Could this include alphabetically organising [main.js](https://github.com/sasstools/sass-lint/blob/master/tests/main.js) so many merge conflicts from that file this time round. :smile:

**Comment by Snugug** [comment]
I'll do you one better; divide each rule in to its own test

**Comment by DanPurdy** [comment]
:heart: 

I was planning on it!

**Comment by Snugug** [comment]
Tracking on https://github.com/Snugug/sass-lint/tree/cleanup/1.2

**Comment by DanPurdy** [comment]
We've got fixes for #125 and #126 ready to go too. Do you want to roll these into 1.2.0 or get a 1.2.1 out straight after?

**Comment by Snugug** [comment]
This rules test rewrite is a surprisingly big job, but on the bright side, I think I can drastically speed up our tests by doing so, in addition to making them easier to maintain

**Comment by Snugug** [comment]
@DanPurdy I think we might as well roll them in to 1.2 as it's not released yet

**Comment by Snugug** [comment]
@DanPurdy @bgriffith What are your thoughts on renaming `color-variable` to `no-color-literals`? The rule, like our other `no` rules, specifically disallows a single thing from happening and you cannot toggle it on or of, activating it toggles it on and that's it.

**Comment by bgriffith** [comment]
If we're only enforcing not using it then I agree with using the `no` prefix. And since `no-color-variable` isn't what we're enforcing `no-color-literals` makes sense to me.

We should also be switching `color-keyword` to `no-color-keyword`.

**Comment by Snugug** [comment]
I believe I already did color keyword

**Comment by DanPurdy** [comment]
I think it makes sense, have you got any thoughts on #126 @Snugug @bgriffith I'm starting to think the extra option for preventing variables being named the same as colour keywords makes a lot of sense..

In the case you mention above with the `no-` prefix it would essentially mean a new rule which I actually think is cleaner IF you think this is necessary as a rule at all..

**Comment by Snugug** [comment]
Generally speaking I'm a fan of smaller, more specific rules over larger rules with configuration options. Configuration options should be reserved only for when the parsing of the rule as a whole is deterministic on the options present (like indentation and quotes).
