### ISSUE TITLE
CSS vars cause `prop.first('ident')` error

### ISSUE THREAD

**Issue by nwpappas** [sasstools/sass-lint#1254]
Using version 1.12.1, I receive the following error:

```
/.../.../node_modules/sass-lint/lib/rules/property-sort-order.js:108
              name = prop.first('ident');
                          ^
```

I've been able to track it down to when defining a CSS var. It happens in multiple locations in my SCSS, but here is one example:

```
:root {
  --theme-bg-opacity: 0.065;
}
```

**Comment by jberkel** [comment]
Looks like duplicate of #1161

**Comment by nwpappas** [comment]
Yes, it is. Thank you for finding that -- I didn't find that one in my search.
