### ISSUE TITLE
[Feature-request] config file : allow "off", "warn", "error" instead of 0, 1, 2 for rule severity

### ISSUE THREAD

**Issue by monkeydri** [sasstools/sass-lint#1265]
It would be consistent with eslint behavior (rules defined in `.eslintrc`).

Currently `sass-lint` fails if using other values than 0, 1 or 2.

- sass-lint 1.12.1

**Comment by glen-84** [comment]
Duplicate of #581.

**Comment by monkeydri** [comment]
damn, sorry for that I missed it.
