### ISSUE TITLE
sass-lint-fix no-vendor-prefixes

### ISSUE THREAD

**Issue by koljagrudinin** [sasstools/sass-lint#1270]
Hello
sass-lint-fix does not supports no-vendor-prefixes

My Sass-lint.yml file contains rule like 

  ```
no-vendor-prefixes:
     - 1
     -
        excluded-identifiers:
        - webkit
        - moz
```

and when i call command

`sass-lint --fix <path-to-any-file>`

i getting error: Rule `no-vendor-prefixes` could not be found!

```
user:frontend user$ node_modules/.bin/sass-lint --fix www_src/scss/_report.scss
/Users/user/Projects/frontend/node_modules/sass-lint-fix/lib/rules.js:61
        throw new Error('Rule `' + rule + '` could not be found!');
        ^

Error: Rule `no-vendor-prefixes` could not be found!
    at /Users/user/Projects/frontend/node_modules/sass-lint-fix/lib/rules.js:61:15
    at Array.forEach (<anonymous>)
    at module.exports (/Users/user/Projects/frontend/node_modules/sass-lint-fix/lib/rules.js:27:29)
    at Function.sassLint.lintText (/Users/user/Projects/frontend/node_modules/sass-lint-fix/index.js:105:15)
    at /Users/user/Projects/frontend/node_modules/sass-lint-fix/index.js:248:23
    at Array.forEach (<anonymous>)
    at Function.sassLint.lintFiles (/Users/user/Projects/frontend/node_modules/sass-lint-fix/index.js:245:12)
    at detectPattern (/Users/user/Projects/frontend/node_modules/sass-lint-fix/bin/sass-lint.js:20:22)
    at /Users/user/Projects/frontend/node_modules/sass-lint-fix/bin/sass-lint.js:84:32
    at Array.forEach (<anonymous>)
```

When i remove this rule - everything is OK

What version of Sass Lint are you using?

 "sass-lint": "^1.12.1",
 "sass-lint-fix": "^1.12.1",

**Comment by srowhani** [comment]
Thanks for reporting this!

As a heads up, at the moment sass-lint has no ties to sass-lint-fix. The published npm package exists as an unmaintained fork of sass-lint.

For the time being, I suggest reporting any issues you have [here](https://github.com/srowhani/sass-lint-auto-fix) instead:

**Comment by mweber92** [comment]
Hey srowhani,
sadly the package becomes unusable if an error stops the hole task. I don't think this is a good behavior if new rules or simply unknown rules like "no-vendor-prefixes" are introduced. 
Generaly a warning would be a better solution.
Or did I get you wrong anyway? Is that a part of "sass-lint-auto-fix" only?

**Comment by srowhani** [comment]
Yes, the latter is correct. The feature being described doesn't exist in sass lint.

**Comment by srowhani** [comment]
Closing this issue for now. Feel free to open, and proceed if you have any further questions!

**Comment by mweber92** [comment]
feature and rule "no-vendor-prefixes" is of cause part of sass-lint? I just don't get it :)
https://github.com/sasstools/sass-lint/tree/master/docs/rules

**Comment by srowhani** [comment]
The repo that he is referring to in an unmaintained fork of sass-lint. It had been published on npm here: https://www.npmjs.com/package/sass-lint-fix

**Comment by mweber92** [comment]
Sorry man. I tought we would discuss this on sass-lint-fix package page... couldn't expect that somone would write this issue inside here. *facepalm* sorry! closed

**Comment by mweber92** [comment]
Ok I got it! Sorry! 🤦‍♂️
