### ISSUE TITLE
outputResults should only do so if warnings or error present

### ISSUE THREAD

**Issue by Snugug** [sasstools/sass-lint#141]
[outputResults](https://github.com/sasstools/sass-lint/blob/develop/index.js#L96-L106) should only output results if there are warnings or errors present.

**Comment by davetgreen** [comment]
Furthermore, if outputting the results to a file is in place it should be silent with the exception of confirmation the results have been generated to the aforementioned file.

**Comment by DanPurdy** [comment]
Master is up to date, will update develop with fixes for the tests and then should be done and good to close.
