### ISSUE TITLE
New Rule: Shorthand

### ISSUE THREAD

**Issue by Snugug** [sasstools/sass-lint#15]
Add test if a property's value should be written as shorthand

**Comment by DanPurdy** [comment]
Made up of 2 rules

* Enforce using the fewest values possible

```scss
margin: 0 2rem 0 2rem

//to

margin: 0 2rem;
```

* Enforce using a shorthand property / value where appropriate

```scss
margin-top : 0;
margin-right: 2rem;
margin-bottom: 0;
margin-left: 2rem;

//to

margin: 0 2rem;
```

## Todo
- [ ] Rule 1 - Enforce shorthand values
- [ ] Rule 2 - Enforce shorthand values and properties

**Comment by DanPurdy** [comment]
Will add the second one here to a new rule
