### ISSUE TITLE
TypeError: Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by idflood** [sasstools/sass-lint#165]
When running `gulp-sass-lint` on my files I get the following error which seems to happen on the last rule. For exemple if I disable the `single-line-per-selector` rule the error happen on a different rule.

    /project_dir/node_modules/sass-lint/lib/rules/single-line-per-selector.js:20
                  'line': next.start.line,
                                    ^
    TypeError: Cannot read property 'line' of undefined
        at /project_dir/node_modules/sass-lint/lib/rules/single-line-per-selector.js:20:33
        at Node.forEach (/project_dir/node_modules/gonzales-pe/lib/node/basic-node.js:1:2053)
        at /project_dir/node_modules/sass-lint/lib/rules/single-line-per-selector.js:13:16
        at RootNode.traverseByType (/project_dir/node_modules/gonzales-pe/lib/node/root-node.js:1:1739)
        ...

    # node --version
    v0.12.5

    # osx 10.10.5

The error is gone if I change the following line: https://github.com/sasstools/sass-lint/blob/develop/lib/rules/single-line-per-selector.js#L16

    if (next && next.start) {

For reference here is a minimal file which cause the error: http://cl.ly/code/1b1o1U1y2q2n
And here the sass-lint.yml: http://cl.ly/code/39022c373X3q

**Comment by bgriffith** [comment]
Have a fix for this so I'll get a hotfix up this evening. Thanks for highlighting @idflood
