### ISSUE TITLE
New Rule: Name Format

### ISSUE THREAD

**Issue by Snugug** [sasstools/sass-lint#17]
Add rule to verify name format:

* Selectors
* Variables
* Functions
* Mixins

**Comment by DanPurdy** [comment]
In the same vein as we discussed with merge able selectors, do we feel these are all separate rules @Snugug ? I think at the very least selectors should be separate to the other 3 but I'm wondering whether 4 rules is excessive before I start on this.

**Comment by benthemonkey** [comment]
I'd like to have a shot at tackling this. For now, if everyone is ok with it, I'll have it parity the configuration options of scss-lint. Sound good, @Snugug @DanPurdy?

**Comment by Snugug** [comment]
Go for it @benthemonkey 

We'd like to split the actual rule out, though, for each type, so `function-name-format`, `mixin-name-format`, `variable-name-format`, `placeholder-name-format`, etc…

**Comment by DanPurdy** [comment]
Yeah go for it. I made a start but hadn't got too far, been a busy week! Definitely 4 separate rules though. Good luck!

**Comment by benthemonkey** [comment]
Looking more carefully at both NameFormat and SelectorFormat from scss-lint, I completely agree with this decision. So the following rules will be added:
`function-name-format`
`mixin-name-format`
`variable-name-format`
`placeholder-name-format`

All having the same options:
`allow-leading-underscore`: boolean (default true)
`convention`: one of `hyphenatedlowercase` (default), `camelcase`, `snakecase`, or RegExp
`convention-explanation`: defaults to `should match regex /[regex]/`

**Comment by DanPurdy** [comment]
Don't forget with parent selectors we should think about BEM style etc. I think the other formats should be ok but selector format will need another step or two!

**Comment by benthemonkey** [comment]
I'm purposely biting off a manageable amount of code to add while I become familiar with contributing. So I've left off adding `selector-format` for now. Once these rules are added, I would like to attempt `selector-format`.

Thanks for the feedback though! I'll definitely keep it in mind.

**Comment by DanPurdy** [comment]
Awesome, looking forward to it. If you need any help just let me know and I'll gladly sort something out!

**Comment by DanPurdy** [comment]
@benthemonkey @bgriffith @Snugug Going to close this issue and setup 3 new separate issues for the remaining rules. Should help us to keep track of what is done and what is not.

**Comment by benthemonkey** [comment]
@DanPurdy don't forget Placeholder Name Format

**Comment by DanPurdy** [comment]
@benthemonkey Added that too now.
