### ISSUE TITLE
Extending more than one class results in error, dependency with an error, gonzales-pe

### ISSUE THREAD

**Issue by smolak** [sasstools/sass-lint#176]
When I try to extend 2 classes, e.g.
`@extend .foo, .bar`
I get an error.

This is due to the fact that dependency used here: https://github.com/sasstools/sass-lint/blob/c6f157f301f342493c1785177b2efb27f566bbb2/lib/groot.js - which is gonzales-pe - has an opened issue: https://github.com/tonyganch/gonzales-pe/issues/21 which is over one year old.

My sollution is either do it manually or change dependency.
As gonzales-pe seems pretty dead, maybe this project could use a different parser (ideally the same as node-sass).

**Comment by Snugug** [comment]
Gonzales [is very much actively maintained](https://github.com/tonyganch/gonzales-pe/tree/dev). Node Sass calls directly in to Libsass which handles the compiling; it doesn't compile itself. Libsass does not provide an AST externally, and it's AST is currently not fine enough to build a linter, even if it were exposed.

**Comment by xzyfer** [comment]
@smolak could you please provide the error and stack trace you're encountering?

gonzales-pe can parse `@extend .foo, .bar` perfectly fine.

**Comment by c089** [comment]
@xzyfer hm, intersting. I'm sure I've seen this, and that issue is also described upstream by someone else: https://github.com/tonyganch/gonzales-pe/issues/21

But this is then not the right place to discuss that I guess. Seems we made a wrong call at calling it dead; I guess we were confused by the github interface which somewhere showed a most recent commit from mid 2014. Sorry about that! I think we can close here.

**Comment by xzyfer** [comment]
@c089 it's hard to grok which issues are still relevant because a bunch of stuff is fixed on the `dev` branch. I was about to patch the extends issue in gonzales but it already did the right thing.

**Comment by xzyfer** [comment]
Could be that it's fixed on master but unreleased.

**Comment by DanPurdy** [comment]
Let's hope theres a new gonzales-pe release soon anyway because there are a few things on the dev branch unreleased that would be really useful to have (tabs support for one!).

Thanks guys I'll close this for now, but feel free to add a new issue if you find this is still causing you problems.
