### ISSUE TITLE
Prefixes array being passed between assertions (no-vendor-prefixes)

### ISSUE THREAD

**Issue by bgriffith** [sasstools/sass-lint#182]
Currently the `prefixes` array in the `no-vendor-prefixes` is not getting reset between assertions. This means that if you modify the array through adding or removing prefixes in an assertion, these changes will still exist for the next assertion.

Was this intended @DanPurdy  Only reason I ask is that the expected number of warnings is only true when this behaviour is allowed.

Easiest way to simulate is to create a new assertion with only the defaults.

SassLint: 1.2.0

**Comment by DanPurdy** [comment]
Hence why there are so many test variations yes.. The only way really to stop this happening currently is to seperate out the tests, not ideal..  I don't think this is too much of a problem as it is, it's testing exactly what we want it to and every case is covered..
