### ISSUE TITLE
New Rule: No @extends

### ISSUE THREAD

**Issue by xzyfer** [sasstools/sass-lint#19]
`@extend` is bad, mmkay?

**Comment by justin-c-rounds** [comment]
Not disagreeing, but please state reasons.

**Comment by Snugug** [comment]
Rules can be toggled on or off. If a user doesn't want to use a given rule, they can disable it.

This is a feature request from a large potential user, so we'll make the rule available

**Comment by xzyfer** [comment]
@justin-c-rounds I feel the case for not using `@extend` is well established, but I'm included some quick resources below for you make your own opinions.

Lastly this project is a linting tool, and does not act as style guide. If you want to use `@extend` this rule wont stop you.

***

http://www.sitepoint.com/avoid-sass-extend/

> Extending is invisible. Extending doesn’t necessarily help file weight, contrary to the saying. Extending doesn’t work across media queries. Extending is not flexible. Mixins have absolutely no drawback.

***

http://sass-guidelin.es/#extend

>However I feel like I must warn you against this feature. As clever as it is, @extend still is a tricky concept that might do more harm than good, especially when poorly used.

***

http://pressupinc.com/blog/2014/11/dont-overextend-yourself-in-sass/

>The problem is not just that there are too many selectors; it’s also that there’s no good way for a human to keep track of which elements are affected by which styling rules.

**Comment by justin-c-rounds** [comment]
Thanks — this is great.

**Comment by filtercake** [comment]
my fav on the topic: [Sass Mixins vs Extends: The Data](https://tech.bellycard.com/blog/sass-mixins-vs-extends-the-data/)
