### ISSUE TITLE
Enhance property-sort-order (other preset orders apart from alphabetical)

### ISSUE THREAD

**Issue by bgriffith** [sasstools/sass-lint#20]
One for a rainy day.. It would be great if we could have a few preset orders to chose from (biased for Recess) when configuring the property-sort-order, similar to scss-lint (https://github.com/brigade/scss-lint/tree/master/data/property-sort-orders) and the config (https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertysortorder)

**Comment by Snugug** [comment]
It's set up to allow for this, just haven't written any yet.

**Comment by minamarkham** [comment]
My config is setup in a custom order:

```
  property-sort-order:
    - 1
    - order:
      - position
      - top
      - right
      - bottom
      - left
      - z-index
      -
      - display
      - float
      - width
      - height
      - padding
      - border
      -
      - color
      - font-family
      - font-size
      - font-weight
      - letter-spacing
      - line-height
      - text-align
      - text-decoration
      - text-shadow
      - text-transform
      -
      - background-color
      - border-radius
      - box-shadow
      -
      - opacity
      - visibility
```

This seems to work, aside from the issue outlined in #13
