### ISSUE TITLE
Space Before Brace docs contain errors

### ISSUE THREAD

**Issue by MethodGrab** [sasstools/sass-lint#219]
On https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-before-brace.md, the title & 1st line are for **space after comma**, not **space before brace**.

I was going to add a quick PR to fix but it seems that's against your contributing guidelines so here are the relevant changes: https://github.com/sasstools/sass-lint/commit/cacb9c4dae7dd8a7f7e56bbc05f8add2cd25d3f4.

**Comment by bgriffith** [comment]
Nice catch! Happy to accept PRs! Which part of the contributing guidelines caught your eye?

**Comment by MethodGrab** [comment]
Sorry I meant without opening an issue first, specifically:
> Do not open a pull request to resolve an issue without first receiving feedback from a collaborator or owner and having them agree on a solution forward.

I've added a PR now.
