### ISSUE TITLE
Absolute configPath is being converted to relative inside sass-lint

### ISSUE THREAD

**Issue by alansouzati** [sasstools/sass-lint#223]
When sending a custom configPath option to sass-lint with an absolute path this gets converted to relative.

I believe that the decision of relative vs absolute should live outside sass-lint so that external paths work as well.

I will send a PR that removes this line https://github.com/sasstools/sass-lint/blob/develop/lib/config.js#L56

**Comment by Snugug** [comment]
Thanks for the issue. Please ensure your solution is discussed and approved by a collaborator before submitting a PR.
