### ISSUE TITLE
Is there an option to hide warnings?

### ISSUE THREAD

**Issue by shaneog** [sasstools/sass-lint#236]
I am refactoring a large code base and I'm initially focussing on clearing the *errors*. Is there a way to hide the warnings from the output?

**Comment by bgriffith** [comment]
Could you not just set all rules with a value of `1` to `0`?

**Comment by shaneog** [comment]
I'm using the `gulp-sass-lint` plugin. 

I suppose I could add exceptions for all warnings, is there a single list for all rules and types?

**Comment by shaneog** [comment]
To explain, I am running `sass-lint` via `gulp` and using `gulp` `watch` which runs the linter when any Sass files are changed. This causes a huge amount of warnings to output to the console, and makes it very difficult to spot errors.

**Comment by bgriffith** [comment]
This is the config containing the full list of rules currently released https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml though it doesn't contain any non-default options. These can be read about in https://github.com/sasstools/sass-lint/tree/develop/docs/rules

**Comment by shaneog** [comment]
Excellent, this issue can be closed so :+1:

**Comment by bgriffith** [comment]
Great!
