### ISSUE TITLE
gonzales-pe updated, sass-lint breaking

### ISSUE THREAD

**Issue by shaneog** [sasstools/sass-lint#245]
It seems that the dev branch of [gonzales-pe](https://github.com/tonyganch/gonzales-pe/tree/dev) was updated 12 hours ago and now sass-lint is choking on Scss which was passing before this. Seems like Sass specific extensions - parent (&) and placeholder (%) selectors.

This issue first presented itself on my CI, with a lot of red builds.

```
../node_modules/gulp-sass-lint/node_modules/sass-lint/lib/groot.js:21
    throw new Error('Parsing error' + fileInfo + ': ' + e.message);
```

**Comment by Snugug** [comment]
Yup, that was quite a big breaking change that was just pushed. Going to need to throw up a hotfix ASAP

**Comment by Snugug** [comment]
Related: https://github.com/tonyganch/gonzales-pe/issues/94

**Comment by shaneog** [comment]
Thanks! Can you do an new npm release of `sass-lint` with the locked down version too please?

**Comment by Snugug** [comment]
yup

**Comment by Snugug** [comment]
Done.
