### ISSUE TITLE
New rule: spacing around bangs

### ISSUE THREAD

**Issue by bgriffith** [sasstools/sass-lint#26]
Allow us to lint the spacing around a bang (before and after). 

Scsslint currently do this with one rule, [bangFormat](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#bangformat), but I feel we should continue in the current style of whitespace rules and have two, `space-before-bang` and `space-after-bang`. Thoughts?

Happy to do this either way  if it gets the thumbs up.

**Comment by Snugug** [comment]
Space before/after bang works for me
