### ISSUE TITLE
New Rule: Force pseudo element/class nesting

### ISSUE THREAD

**Issue by DanPurdy** [sasstools/sass-lint#268]
As discussed in #256

Rule should enforce the nesting of pseudo elements/classes

**Comment by esr360** [comment]
> A value of `0` is not allowed. `zero` must be used

This seems wrong to me? Setting this to `zero` should surely allow `0` instead of `none`? As far as I'm aware `border: zero` is not valid.

**Comment by DanPurdy** [comment]
@esr360 sorry, what are you referring to and where?

**Comment by esr360** [comment]
Sorry @DanPurdy I posted this on the wrong issue, I had another relevant issue open relating to this, I meant to post this here: https://github.com/sasstools/sass-lint/issues/861

I will open a new issue though.

**Comment by DanPurdy** [comment]
It's ok no problem, just got a little confused! 👍

**Comment by DanPurdy** [comment]
Hey @esr360 I've put a PR in to address your issue, feel free to add any comments there if you feel necessary. see #926
