### ISSUE TITLE
New Rule: Color Variables

### ISSUE THREAD

**Issue by Snugug** [sasstools/sass-lint#27]
As per [SCSS Lint](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#colorvariable)

**Comment by DanPurdy** [comment]
Looking at this one.

**Comment by DanPurdy** [comment]
So... I have a question about this one. We are going to need to check each value against a list of all the css colors, I'm feeling like this should be a seperate text or yaml file ala scss-lints property listings. Any preference to how we do this?

**Comment by DanPurdy** [comment]
Went with separate YAML file.. will open PR soon, just a little more testing.

**Comment by DanPurdy** [comment]
Ready to go just waiting for @bgriffith to fix his conflicts on #81 then I'll get the PR rolling.
