### ISSUE TITLE
New Rule: Selector Format

### ISSUE THREAD

**Issue by DanPurdy** [sasstools/sass-lint#275]
Add rule to verify name format of selectors.

Please see the original issue for more information and discussion #17

**Comment by benthemonkey** [comment]
I'm going to start working on this one, although I expect it will take longer than the other format rules.

**Comment by mik01aj** [comment]
+1 for this idea.

I'd like to add, that in my project we want that every css rule applies to some specific React component. For example, for a component named `UserAvatar` (component names in React always start with uppercase letter), I'd like all the css to be wrapped in `.UserAvatar { ... }` block.

It would mean that it is important for me whether it operates on compiled selectors, or selectors as found in source code. For this specific rule, it would be better if the rule would check that every **compiled** selector matches a regex `\.[A-Z][a-z]+.*` - but I can also imagine that people would like to match their rules as in source code.

**Comment by DanPurdy** [comment]
So I did some work on compiling selectors for the `mergeable-selectors` rule you may find some ideas there if needs be. I agree that BEM and all the different styles people write may be tricky but it will be great to get this one done! Looking forward to it.

**Comment by benthemonkey** [comment]
So scss-lint lets you specify different conventions for ids vs classes, etc. Should this rule be broken up into multiple rules? `class-name-format`, `id-name-format`, and `attribute-name-format`?

**Comment by Snugug** [comment]
Yah, I'm ok with that

**Comment by benthemonkey** [comment]
Closing this issue and setting up three separate issues

**Comment by mik01aj** [comment]
@benthemonkey I like how you split this issue into 3, but how about compiled selectors (or matching structure)? Should I open one more for this?

**Comment by DanPurdy** [comment]
If you feel there is a rule you'd like to see added then yes, please open a separate issue to discuss it. If you can provide as much information about what you'd expect the rule to be checking for and what you'd like to see from it then we can discuss it there.

Thanks

**Comment by benthemonkey** [comment]
Thanks for jumping in, @DanPurdy. @mik01aj I didn't want to say yes or no to you as I've been contributing for barely over a week.

**Comment by mik01aj** [comment]
@benthemonkey I will think about it, as for now I don't have a clear idea of a config API for such a rule.

One more thing: you missed **tag name format**. Tags are mostly html, but some frameworks make heavy use of custom html tags (e.g. Angular) so it would make sense to match them too. I don't know how important it is to others (and well, if you ask me... I don't use Angular anymore :stuck_out_tongue_winking_eye:).
