### ISSUE TITLE
Rename Rule one-declaration-per-line to single-line-per-property

### ISSUE THREAD

**Issue by BPScott** [sasstools/sass-lint#288]
Scss-lint has a rule called [SingleLinePerProperty](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#singlelineperproperty), which is functionally identical to our existing rule [one-declaration-per-line](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/one-declaration-per-line.md). For the sake of consistency would it be worthwhile renaming the existing rule to match scss-lint's naming?

This caused some confusion when I opened #283 requesting the Scss-lint rule to be added after not finding an that named rule in sass-lint's rules, only to find it did exist, just named differently.

Related question: What is Sass-lint's stance on compatibility with scss-lint? Should it be trying to mimic all existing features to become a drop-in replacement or is scss-lint going forging it's own path? In either case should we attempt to share naming conventions where possible?

**Comment by Snugug** [comment]
I specifically did not carry over the name syntax as it does not accurately describe what our rule enforces. While it enforces single line per property, it also (should) enforce single mixin per line and single variable per line, which are not properties but rather declarations.

**Comment by Snugug** [comment]
We also have a slightly more declarative naming convention for our rules, which `single-line-per-property` wouldn't quite match

**Comment by Snugug** [comment]
To answer your second question, we are aiming for feature parity, not config parity, while working towards the mental model of ESLint (small, discrete rules with few exceptions that are always strict unless a user specifically says otherwise) which may result in some minor changes between the way items are linted.

**Comment by DanPurdy** [comment]
`single-line-per-declaration` would better match and at the same time be consistent naming with the `single-line-per-selector` rule. Either that or we should rename `single-line-per-selector` to `one-selector-per-line`, Personally I prefer the former.

**Comment by Snugug** [comment]
We are not checking that a property only spans one line, like `single-line-per-property` suggests, but rather that there is only one property on a given line. The former is just ambiguous enough to cause problems, where the later is unambiguous.

**Comment by DanPurdy** [comment]
Yeah you're right, so do we think that the selector rule should be similarly named then? I mean I know they can't span multiple lines but the intention is the same?

**Comment by Snugug** [comment]
Yah has that rule officially been released? If not, we should rename it before 1.3. If so, we need to keep it around and document that users should move to the new name as to not introduce a breaking change, and we can officially deprecate the old name in 2.0

**Comment by DanPurdy** [comment]
Yeah, I think it was part of `1.0`. So do we duplicate the rule and have the previous rule also output a deprecation warning or do we just remove it's functionality but leave a warning that would always output when used but not actually report any other errors?

**Comment by Snugug** [comment]
@DanPurdy Let's open a new issue to track this. Rename current rule and update as needed, use `require` to bring updated rule in to deprecated rule, and add a `console.log` non-blocking warning to the top of the deprecated rule file.
