### ISSUE TITLE
New Rule: Import Path

### ISSUE THREAD

**Issue by Snugug** [sasstools/sass-lint#29]
As per [SCSS Lint](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#importpath)

Probably want a more descriptive name

**Comment by bgriffith** [comment]
Got this working locally. Any ideas on a more descriptive name? I've used import path for now. I has two defaults like the scss lint version. Leading underscores and file extensions.

**Comment by Snugug** [comment]
Maybe `clean-import-paths`?
