### ISSUE TITLE
Add link to scss-lint config converter in README?

### ISSUE THREAD

**Issue by benthemonkey** [sasstools/sass-lint#299]
I don't mean to self-promote, but I think this tool I've been working on would be useful for folks moving to sass-lint from scss-lint:

http://benthemonkey.github.io/make-sass-lint-config/

Maybe include a link to the tool in the README?

I don't know how this sort of thing works, but would this tool be something valuable to move into the sasstools organization?

**Comment by Snugug** [comment]
I would love to see this integrated in to Sass Lint! Thoughts on working to integrate it directly in instead of a stand-alone tool/site?

**Comment by bgriffith** [comment]
Hah just the other day I was chatting with @DanPurdy about a sass lint configure generator! Has my full support!

**Comment by DanPurdy** [comment]
Haha,  stole my thunder!!! 

Yeah this would be awesome, standalone site to start but was definitely thinking that a part of the cli could parse a scss-lint file and transform it into a sass-lint file! I'd happily contribute to this @benthemonkey

**Comment by DanPurdy** [comment]
If we do include this as a CLI tool / part of sass-lints CLI I still think it would be worth making this into a seperate package that we pull in as a dependency, would allow us to extend it into further tools if needed!

**Comment by benthemonkey** [comment]
Just let me know how to proceed. I'm up for doing things either way.

**Comment by DanPurdy** [comment]
@benthemonkey I've asked the other guys to look back at this again, personally I think we should get a PR to add this into the README then look to move this under the sasstools org as a js module that we could use in a range of projects that might want to convert scss-lint configs to sass-lint ones.

**Comment by Snugug** [comment]
That sounds like a plan to me.

@benthemonkey if you add me as an admin to that project, I can move it over to Sasstools if that sounds good to you.

**Comment by benthemonkey** [comment]
I transferred ownership of the repo to you, I didn't see another way to give you admin rights since it wasn't part of an organization.

**Comment by benthemonkey** [comment]
would it be possible for me to be an admin of that repo inside sasstools and not the other repos?

**Comment by benthemonkey** [comment]
I'll turn it into a module, publish to NPM, add unit tests, etc.

**Comment by DanPurdy** [comment]
Quick! Now we own it ban him!! :smile:
