### ISSUE TITLE
Can't get property sort order to work with sublime

### ISSUE THREAD

**Issue by wroughtec** [sasstools/sass-lint#306]
I have installed this and sublime linter  and relevant sass plugin

However when I have created a yml file with a custom property order it still shows an error on my ordering:

    $white: #fff;

    .class {
      position: absolute;
      top: 100px;

      display: block;
      height: 100%;

      text-align: left;
    }

Order is defined as:

    property-sort-order:
        - 1
        - order:
          - position
          - top
          - right
          - bottom
          - left
          - z-index
          -
          - display
          - float
          - width
          - height
          - padding
          - border
          -
          - color
          - font-family
          - font-size
          - font-weight
          - letter-spacing
          - line-height
          - text-align
          - text-decoration
          - text-shadow
          - text-transform
          -
          - background-color
          - border-radius
          - box-shadow
          -
          - opacity
          - visibility

But whatever I have tried in sublime I am getting an error and its trying to be alphabetical any suggestions?

**Comment by bgriffith** [comment]
Could you test if it works without spaces? May be a bug

**Comment by wroughtec** [comment]
Removing space has not affect

**Comment by Snugug** [comment]
Can you try just through the command line? If I were to guess its a problem with the Sublime Text plugin if it works there, and you should file a bug with them

**Comment by DanPurdy** [comment]
Closing this to lack of info
