### ISSUE TITLE
New Rule: Space Around Operator

### ISSUE THREAD

**Issue by Snugug** [sasstools/sass-lint#31]
As per [SCSS Lint](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#spacearoundoperator)

**Comment by bgriffith** [comment]
What do you think about going down the ESLint way with this rule? It's called [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops).

I've had a go at this too, most are sorted but currently having trouble targeting the `%` for mod...

**Comment by Snugug** [comment]
Infix is such a :neckbeard: way of describing those operators (and to the best of my knowledge, Sass doesn't allow prefix or postfix operators), I'm afraid the name won't make sense to most people who want to use it

**Comment by bgriffith** [comment]
Haha fair enough! Space Around Operator *is* a lot more descriptive.

**Comment by bgriffith** [comment]
Since this went quiet, I'll bring my branch back from the dead and get rule sorted :rocket:

**Comment by DanPurdy** [comment]
Yeah the other one didn't work with Sass at all so I closed it and never heard anything back.
