### ISSUE TITLE
Refactoring the helpers test suite

### ISSUE THREAD

**Issue by bgriffith** [sasstools/sass-lint#322]
Having recently added to the helpers test file it became apparent that it needs a good refactor and in my opinion splitting up into multiple files, with a similar folder/file structure to that of the rules. While there aren't that many at the moment, I think to do it now would only be beneficial in the future.

So if anybody doesn't have any objections, I'll look get going on this.

**Comment by DanPurdy** [comment]
Sounds good, go for it.
