### ISSUE TITLE
New Rule: Class Name Format

### ISSUE THREAD

**Issue by benthemonkey** [sasstools/sass-lint#324]
Add rule to verify name format of class selectors.

Please see the original issue for more information and discussion #17 and #275

**Comment by gitnik** [comment]
Would be cool if this would include a `BEM` naming convention by default

**Comment by BPScott** [comment]
@gitnik: Check the docs in the associated PR, [BEM convention is already in there](https://github.com/benthemonkey/sass-lint/blob/feature/class-name-format/docs/rules/class-name-format.md#example-5)

**Comment by gitnik** [comment]
Sweet! Thanks
