### ISSUE TITLE
Inconsistent rule name (url-format vs no-url-protocols)

### ISSUE THREAD

**Issue by mik01aj** [sasstools/sass-lint#335]
The `no-url-protocols` rule has another name in the code:

![screenshot 2015-10-20 16 21 46](https://cloud.githubusercontent.com/assets/3027415/10610106/b755d5f0-7746-11e5-980a-913963cacac1.png)

https://github.com/sasstools/sass-lint/blob/bd5861fcee211591cf8adf9c10495f544a84c26f/lib/rules/no-url-protocols.js

This means that `no-url-protocols` setting in the config is ignored, and `url-format` will be respected. This is not what the docs say.

**Comment by bgriffith** [comment]
Thanks, good catch.

**Comment by bgriffith** [comment]
OK PR pushed, thanks again.

**Comment by mik01aj** [comment]
:+1:

**Comment by DanPurdy** [comment]
Ooops, I actually noticed this the other night and meant to fix it up.. Thanks @mik01aj !
