### ISSUE TITLE
hex-length is wrong about how short hexes work

### ISSUE THREAD

**Issue by benthemonkey** [sasstools/sass-lint#341]
The test cases and code suggest that the following hex values are equivalent:
`#a2c == #a2ca2c` <= wrong

That's not how it works... This is how it works:
`#a2c == #aa22cc`

(Here's a source: https://www.w3.org/community/webed/wiki/CSS_shorthand_reference#Color)

**Comment by DanPurdy** [comment]
Wow, I don't even know how I managed that! My bad..
