### ISSUE TITLE
function-name-format doesn't take exception to CSS transform functions

### ISSUE THREAD

**Issue by benthemonkey** [sasstools/sass-lint#344]
The following are all valid function names, regardless of the `convention` used:
- rotateX
- rotateY
- rotateZ
- scaleX
- scaleY
- scaleZ
- skewX
- skewY
- translateX
- translateY
- translateZ

**Comment by BPScott** [comment]
Do we also need to add exceptions for CSS functions that use the hyphenated-lowercase convention, such as `linear-gradient` and `radial-gradient`?

Searching https://developer.mozilla.org/en-US/docs/Web/CSS/Reference for `()` shows functions available, but I'm not sure if that's an exhaustive list.

**Comment by bsteffl** [comment]
I think @BPScott comment is still a valid issue.

**Comment by benthemonkey** [comment]
Thanks! I opened a separate issue: #434
