### ISSUE TITLE
Disabling lint rules via source comments

### ISSUE THREAD

**Issue by natorojr** [sasstools/sass-lint#365]
Is it possible to disable a rule via source comments (either on file-by-file or line-by-line basis)?

More specifically, I need to be able to disable some rules on a specific vendor file. I used to do this with scss-lint as follows https://github.com/brigade/scss-lint#disabling-linters-via-source

If not currently supported, could something like this be implemented for sass-lint?

**Comment by bgriffith** [comment]
Hey @natorojr  - I think this is on the cards. Here's the ongoing discussion https://github.com/sasstools/sass-lint/issues/70

**Comment by natorojr** [comment]
Ah, thanks for the link @bgriffith. My initial search didn't find this issue.

I'm closing this in favor of #70 since it's exactly the same request.
