### ISSUE TITLE
New rule: Property units

### ISSUE THREAD

**Issue by bgriffith** [sasstools/sass-lint#371]
One rule that we are missing is one to lint which units can be used with specific property values.

SCSS Lint currently does this with https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertyunits though I'm undecided if this is the best way, or if we should consider breaking it up into multiple unit managing rules.

Open to thoughts

**Comment by DanPurdy** [comment]
I was looking at this the other day, I think it would be a mistake to split this into a per property rule, i.e. a separate rule for border units, margin units etc, there would be so much duplication and complication for users and would make it difficult to implement global units.

**Comment by bgriffith** [comment]
Closed with #387
