### ISSUE TITLE
Support excluding specific styles from no-vendor-prefixes rule

### ISSUE THREAD

**Issue by maxlapides** [sasstools/sass-lint#374]
I like using `-webkit-font-smoothing`. Right now, I can't think of a way to keep the `no-vendor-prefixes` rule enabled while still allowing my code to pass. It would be nice if there were some way to exclude specific styles from this rule in addition to entire prefixes. What do you all think?

**Comment by DanPurdy** [comment]
I dont think we should add any whitelisting to this rule for occasions like this, the rule is either enable or disable, this would be the ideal scenario for something like #70 which we do plan on getting done I just know all of the contributors have been very busy recently..

**Comment by DanPurdy** [comment]
Just noticed this issue again, 1.8.0 should be sufficient to address this see #709 for details
