### ISSUE TITLE
Add feature to set syntax passed to gonzales via CLI --syntax option

### ISSUE THREAD

**Issue by donabrams** [sasstools/sass-lint#381]
As per https://github.com/skovhus/SublimeLinter-contrib-sass-lint/issues/4, we have a need to override the syntax and not use the file-detected syntax based on extension.

Expected: `sass-lint --syntax scss a.txt` will use scss syntax and `sass-lint --syntax sass a.txt` will use sass syntax.

Naive implementation here (since PRs must wait...): https://github.com/sasstools/sass-lint/compare/develop...donabrams:develop

**Comment by DanPurdy** [comment]
HI @donabrams I had a read through your issue [here](https://github.com/skovhus/SublimeLinter-contrib-sass-lint/issues/4) it does seem like a very odd thing for sublimelinter to be changing the syntax of a file when it gets saved as a tmp file, have you filed an issue with them?

As for our end of it I can't really classify it as a bug as it's treating a .sass file as Sass syntax which is correct but I do see that this option would solve your needs and may also account for a few other strange errors we've seen mentioned recently (assuming now that they must of come from the sublime plugin!).

I'm going to ping @Snugug into the conversation here to check this over from a 'do we want/need this behaviour' but I'd be happy for you to submit that PR to our develop branch. 

Initial thoughts on your changes would be just to make sure you add the option to the [CLI docs](https://github.com/sasstools/sass-lint/tree/develop/docs/cli) too.

Thanks again!

**Comment by Snugug** [comment]
This is tough as it'll solve your problem, but has a very real potential to be weird for globbed results. That being said, I can also see how it could be useful for other use cases like a pipeline that relies on file extensions for processing (Rails does this I believe?). Oh the castles we build on sand!

Anyway, yah, sure, issue a PR. There's no harm in having it as a CLI option if it'll solve your problem and doesn't break anything else. I'd also file a bug with SublimeLinter cause, like @DanPurdy said, that sounds like a crappy bug on their end.

**Comment by DanPurdy** [comment]
This should of been closed a while ago as it's been a feature for a while now.
