### ISSUE TITLE
Indentation rule - Incorrect mixed spaces / tabs warnings

### ISSUE THREAD

**Issue by DanPurdy** [sasstools/sass-lint#382]
So this is two issues really, first raised in #373

sass-lint @ 1.3.2
node @ any version

The error being thrown in #373 is because it's checking for a non [existent node content](https://github.com/sasstools/sass-lint/blob/develop/lib/rules/indentation.js#L57) block when files are using `CRLF` line endings.

This seems to actually hide the real issue though which is an issue where `CRLF` endings are throwing false mixed spaces and tabs warnings. On first look this is due to the regex for whitespace matching new line characters when dealing with `CRLF` as we're manually slicing the content array and only taking into account the length of `\n` rather than `\r\n` as well. 

Use the file uploaded in #373 and make sure your editorconfig/IDE doesn't auto format the line endings and you'll be able to test this.

**Comment by mlenser** [comment]
Definitely experiencing this on Windows. Please fix.

**Comment by EnoahNetzach** [comment]
I'm experiencing this also with a sequence of \n\t (using a tab character after a LF)

**Comment by mlenser** [comment]
@bgriffith does this also fix the CRLF issue on windows?

**Comment by DanPurdy** [comment]
@mlenser Yes it will do, we test every rule with CRLF line endings on Appveyor as well as LF on Travis now. We'll release this in 1.8.0. I fixed an issue with the AST that means CRLF should be providing correct warnings across the board now.

I've also added support for tabs with the indentation fixes.

Keep an eye out for 1.8 👍

**Comment by mlenser** [comment]
@DanPurdy Awesome! Thank you so much!!
