### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by hochitom** [sasstools/sass-lint#389]
just installed latest sass-lint version. but it throws an error, when I start it

node_modules\sass-lint\lib\rules\indentation.js:57:46

**Comment by DanPurdy** [comment]
Hi @hochitom. Can you give us a little more information here please, such as whether you're using tabs or spaces and what types of line endings you're using, I've got a feeling it's going to be related to #373 and #382

**Comment by SrTobi** [comment]
We got the same problem in our Project (https://github.com/HelfenKannJeder/come2help-web). It appears on Windows 10 but not on Ubuntu 15.10. Here is the [.sass-lint.yml](https://github.com/HelfenKannJeder/come2help-web/blob/master/css/.sass-lint.yml).

```
C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\lib\rules\indentation.js:57
                  'line': node.content[i + 1].start.line,
                                             ^
TypeError: Cannot read property 'start' of undefined
    at processNode (C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\lib\rules\indentation.js:57:46)
    at Object.module.exports.detect (C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\lib\rules\indentation.js:100:5)
    at C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\index.js:44:27
    at Array.forEach (native)
    at Function.sassLint.lintText (C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\index.js:43:11)
    at C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\index.js:91:21
    at Array.forEach (native)
    at Function.sassLint.lintFiles (C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\index.js:90:9)
    at detectPattern (C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\bin\sass-lint.js:15:18)
    at Object.<anonymous> (C:\Users\Tobias\Documents\Work\come2help-web\node_modules\sass-lint\bin\sass-lint.js:77:3)
```

We fixed the problem by changing the line ending from crlf to lf of the scss files.

**Comment by DanPurdy** [comment]
Thanks @SrTobi this is something I've noted in #382 the error you're seeing is hiding another error and as you rightly say, changing from crlf to lf fixes the issue. 

We'll look into it.

**Comment by kvz** [comment]
Ran into the same thing. I had to run both `dos2unix` and `tab2space -unix -t2` on my scss files to work around this. I do agree I should only have `\n` and `  ` for whitespace in my files, but maybe this can be turned into another check.

**Comment by DanPurdy** [comment]
Hi @kvz Our problem is that we're limited by our AST's support of tabs in general at the moment and we're a little reluctant to keep updating the indentation rule. We'd like to support all line endings and whitespaces but we need to wait on our AST becoming stable in it's latest incarnation.

**Comment by abritinthebay** [comment]
Simple fix for this would be changing

`if (count !== spaceLength)` on line 57 of indentation.js to `if (count !== spaceLength && node.content[i + 1]) `

little bit hacky I know but it does mean that it actually appears to... you know... work. Right now it's just unusable :(

**Comment by mischkl** [comment]
Any chance this will be fixed in the next release? Even with the indentation rule turned off I get this error, so sass-lint is completely useless for us (on Windows) atm.
