### ISSUE TITLE
New Rule: BEM Depth

### ISSUE THREAD

**Issue by benthemonkey** [sasstools/sass-lint#413]
Name: `bem-depth`
Option: `max-depth`, defaults to 1

Add a rule that enforces a maximum number of elements in a BEM selector.

Note that the option name, `max-depth` is different from scss-lint, which calls the option `max_elements`. This way the option is consistent with nesting-depth, and soon selector-depth).

The helper function I wrote, `collectSuffixExtensions`, should make this fairly straightforward to implement.

**Comment by DanPurdy** [comment]
Yeah was thinking this after reviewing your class name one, shouldn't be too tough at all.

Also, while i admire your enthusiasm try not to self assign too many issues before you start on them as there's already a few with your name on for [1.4.0](https://github.com/sasstools/sass-lint/milestones/1.4.0) and assigning more may put others off from contributing or starting to work on them. No one will tackle rules that look like they may already be in progress. I've been guilty of it too in the past! :smile:

**Comment by benthemonkey** [comment]
Will do. `id-name-format` just needs a few finishing touches once `class-name-format` gets merged. And I've started on this rule before creating the issue. I'll take myself off `selector-validity` until I know I'll have time for it.

It's also not entirely fair to point out the milestone when it wasn't set by me :tongue:

**Comment by DanPurdy** [comment]
I don't know where the date on that milestone came from either I just happened to be looking at it but I think you misunderstand my point, im not trying to say anything like you need to do these first, it's up to you what you work on and I'm glad you're contributing so much to the project but I'm just mentioning with a few rules with your name on them in the 1.4 pipeline no one would tackle them in thinking that you have them covered, it was just a friendly thought. I'll re look at class name tomorrow so you can get these up and running. Nice one
