### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by Snugug** [sasstools/sass-lint#42]
Make Sass Lint run-able via a command line command. The [CLI Branch](https://github.com/sasstools/sass-lint/tree/cli) is where work is being done on this feature.

- [x] Do not fail on error

## Feedback Requested

What options should be available from the command line?

**Comment by davidgilbertson** [comment]
+1

Could it maybe be added to the readme that there isn't a CLI yet? I'm guessing you're about to have thousands of eager devs trying to get it working before realising that there is no CLI.

Also, this whole `sass-lint` thing is awesome, congrats on the 1.0 release!

**Comment by Snugug** [comment]
Done
https://github.com/sasstools/sass-lint/blob/master/README.md#cli

**Comment by Snugug** [comment]
Track progress on the CLI Branch
https://github.com/sasstools/sass-lint/tree/cli

**Comment by davidgilbertson** [comment]
Nice.

My thoughts on command line options would be to more-or-less mirror `scss-lint`. Of those the two I can imagine using would be:

* `--config` so that I can define a config file other than the default.

* `--exclude`

* I'm tempted to say a `--files` option to override the glob in the config file, but can't think of a use case.

**Comment by Snugug** [comment]
So currently, this is how the CLI is shaping up:

* `sass-lint` will use whatever is in the config file
* `sass-lint '<file or glob'>` will override the file or glob from the config file
* `--no-exit` will prevent the CLI from failing if there's an error

The config currently calls `exclude` `ignore`; I can swap them if need be and add that as an option.

I'm going to wait on https://github.com/sasstools/sass-lint/issues/47 to land before providing a CLI for custom config.

**Comment by Snugug** [comment]
Custom Config file landed in the CLI branch, so this'll be part of the CLI when released

**Comment by davidgilbertson** [comment]
Sounds perfect. Do you have a ballpark ETA on this? Weeks, months?

**Comment by Snugug** [comment]
Probably days. It's working, just needs final tweaks.
