### ISSUE TITLE
Space around operator issue

### ISSUE THREAD

**Issue by DanPurdy** [sasstools/sass-lint#425]
@bgriffith another one for you! ;)

Finding even more errors from `space around operator`, luckily it's not live yet..

You can recreate this issue by running space around operator against the shorthand values test `scss` file.

this line throws the issue

```
.value-four-diff-four-negative-mixed {
  margin: -1px 1px -1rem -1rem;
}
```

![screen shot 2015-11-20 at 17 56 26](https://cloud.githubusercontent.com/assets/1386054/11307445/1a89487e-8fb0-11e5-977e-bda8ee16e999.png)

**Comment by DanPurdy** [comment]
Welllll this is embarrasing...this is my mistake. Using the wrong global package for something I was testing out... 

Your latest fix dealt with this issue @bgriffith 

Sorry!

**Comment by DanPurdy** [comment]
Nope @bgriffith this is definitely still causing issues.. Run it against EB and you'll see.

**Comment by DanPurdy** [comment]
OK @bgriffith I'm still seeing an issue here. Run it against the typography file in default section of EB and you'll see what I mean..

![screen shot 2015-11-22 at 01 16 34](https://cloud.githubusercontent.com/assets/1386054/11321423/c01b6298-90b6-11e5-8001-8efb5856af3e.png)

**Comment by bgriffith** [comment]
Just for reference it's this line here not the above.

`$a-font-color-hover: scale-color($a-font-color, $lightness: -14%) !default;`
