### ISSUE TITLE
Study lesshint's discussion of gonzales-pe, consider switching to PostCSS (and writing our own parser(s))

### ISSUE THREAD

**Issue by benthemonkey** [sasstools/sass-lint#427]
The people over at [lesshint](https://github.com/lesshint/lesshint) have been [researching and discussing a move away from gonzales-pe](https://github.com/lesshint/lesshint/issues/89). They are very methodical in their approach.

They have [forked gonzales-pe](https://github.com/gilt/gonzales-pe) to suit their specific needs, and are developing a PostCSS extension, [postcss-less](https://github.com/gilt/postcss-less), to use instead of gonzales-pe in the future. Their main concern was the difficulty in contributing to/debugging gonzales-pe, and what that may mean for the future stability of the library. I'm not sure if anyone else has tried fixing gonzales-pe themselves, but I agree with [shellscape's conclusion](https://github.com/lesshint/lesshint/issues/89#issuecomment-152053445) that gonzales-pe wasn't written for collaboration.

There is a library which started work on a [PostCSS parser for SCSS](https://github.com/postcss/postcss-scss), but it doesn't seem to actually parse things like parent selectors or interpolation. It's possible that xzyfer is working on a PostCSS fork for Less, Sass and SCSS already (I found [this comment](https://github.com/postcss/postcss-scss/issues/1#issuecomment-129660784), but I can't find any such repo). I played around a little with the AST generated by PostCSS, and it does seem much easier to use than gonzales-pe's. The source code of postcss-scss is also very easy to read and understand.

This would be a large undertaking. This Issue is to get a discussion started now, because it would be even more difficult to make this switch after 2.0, IMO.

**Comment by Snugug** [comment]
Check the other Sass Tools repos. Already have some working.

https://github.com/sasstools

Already on the roadmap, but we're not going to switch to anything that doesn't have sass support as well as scss support and currently PostCSS isn't granular enough to move to. @xzyfer is working on it.

~ Sam Richard
(775) 476-8484
http://snug.ug

**Comment by benthemonkey** [comment]
I certainly don't want to duplicate work. As I mentioned, I was having trouble finding xzyfer's progress on this. Is it private?

The repos in sasstools seem to predate work that was done in PostCSS to support custom syntaxes (see this doc file: https://github.com/postcss/postcss/blob/master/docs/syntax.md). What granularity is PostCSS missing?

The easy option is to wait and see how postcss-less progresses and decide based on their success. But I thought their discussion was relevant to us.

**Comment by Snugug** [comment]
He says he has a bunch of work done on it but it's not pushed yet. Throw an issue in there and ask

**Comment by benthemonkey** [comment]
Sorry, where should I throw an issue?

**Comment by Snugug** [comment]
https://github.com/sasstools/scss-tokenizer appears to have the most work done on it. I'd start there.

**Comment by xzyfer** [comment]
Sorry I've been away. I have started work on a replacement for gonzales-pe. It's very early days has been neglected due to my work on LibSass.

As @Snugug mentions the PostCSS route is not viable for Sass projects because there are assumptions in the PostCSS that don't play nice with .sass syntax. Also adopting a PostCSS solution would require much more logic around parsing Sass to live within sass-lint or an intermediary tool because PostCSS has a very low resolution in it's default AST tree.

These are all issue I plan to tackle in Jamble. If you want to help out I'm happy to discuss my thoughts, progress, and plan moving forward.

**Comment by benthemonkey** [comment]
Thanks for the update. I'll certainly defer to yours and @Snugug's expertise when you say PostCSS won't be a good fit for Sass. I am interested in contributing, but probably not until January. I'll contact you then, @xzyfer.
