### ISSUE TITLE
Please cut a new release for Property Units

### ISSUE THREAD

**Issue by una** [sasstools/sass-lint#444]
Property units is included: https://github.com/sasstools/sass-lint/blob/develop/lib/rules/property-units.js but not a part of the *1.3.3* release. Please cut a new release with it included

**Comment by DanPurdy** [comment]
HI @una yeah sorry about the delay, 1.3.3 was just a patch release. There's quite a lot of unreleased stuff at the moment for 1.4.0 https://github.com/sasstools/sass-lint/issues?q=milestone%3A1.4.0+is%3Aclosed

We intended to release 1.4.0 a long time ago just as everyone seemed to get swamped!

There's 2 outstanding issues for 1.4, one is ready to merge and one is needing a quick update, once those are done we'll get it released.

**Comment by hellobrian** [comment]
+1

**Comment by DanPurdy** [comment]
This will be happening in the next few hours..

**Comment by DanPurdy** [comment]
Hi @una & @hellobrian thanks for your patience. v1.4.0 is out now. Hope it's all good for you.

**Comment by hellobrian** [comment]
:clap: :clap: :clap: :clap: woot! thanks!
