### ISSUE TITLE
IDE Integration for WebStorm

### ISSUE THREAD

**Issue by tsm91** [sasstools/sass-lint#460]
There is a webstorm plugin for [scss-lint](https://plugins.jetbrains.com/plugin/7530?pr=) already. It would be awesome to see a `sass-lint` plugin also. :)

**Comment by DanPurdy** [comment]
Hi @tsm91 it would be good to see definitely, but you'll need to find a java developer for that. If anyone wants to do this under the sasstools name then I'm sure @Snugug would welcome it into the organisation! As for now though, this isn't really an issue that's related to `sass-lint` itself so I'm going to close this. 

Thanks

**Comment by tsm91** [comment]
@DanPurdy alright, fair enough. I am sure eventually someone will create one. I try to contact ido, the creator of scss-lint.

**Comment by DanPurdy** [comment]
Awesome, we'd love to see it. Thanks @tsm91

**Comment by tsm91** [comment]
Cool, i've contacted him. Lets hope for the best. :)
