### ISSUE TITLE
Request - Add Visual Studio Code IDE support?

### ISSUE THREAD

**Issue by jaminroe** [sasstools/sass-lint#463]
With Visual Studio Code up and coming, would be really nice if we could support that IDE as well. Thanks! 😊

**Comment by DanPurdy** [comment]
Hi there,

Unfortunately this repo is just for `sass-lint` itself and the issues section is for tracking any `sass-lint` issues. IDE integrations need to be handled or requested elsewhere I'm afraid, the current IDE integrations have all been developed externally and not currently on our teams radar (apart from the [atom](https://github.com/AtomLinter/linter-sass-lint) one which I built :smile: ). If someone wants to build an integration and host it under the sasstools team then their best bet is to speak with @Snugug, I'm sure he'd be more than happy to have it here.

As for now I'll close this issue to keep on topic.

Thanks!

**Comment by jaminroe** [comment]
Oops, sorry! 😅No problem!
