### ISSUE TITLE
PropertySortOrder - Why by default height property is before width?

### ISSUE THREAD

**Issue by cht8687** [sasstools/sass-lint#467]
Hi, I know now we can do custom order: https://github.com/sasstools/sass-lint/pull/113
I am wondering why by default height property is before width? Didn't get any information related to this topic but it would be great that some one can explain this.

**Comment by BPScott** [comment]
If you enable the the PropertySortOrder rule but don't specify a particular ordering then the default sort order is alphabetical, 

https://github.com/sasstools/sass-lint/blob/develop/docs/rules/property-sort-order.md

**Comment by cht8687** [comment]
oh, thank you @BPScott.
