### ISSUE TITLE
Add Brackets integration to the IDE Integration list 

### ISSUE THREAD

**Issue by petetnt** [sasstools/sass-lint#470]
Hey there,

I created [brackets-sass-lint](https://github.com/petetnt/brackets-sass-lint) for interactive SASS/SCSS linting in [Brackets](http://brackets.io) that is powered via `sass-lint`.

If you would be kind enough to add it to the IDE Integration list on `README.md` that would be neat, if not, that's okay too :smile_cat: 

I'll have an accompanying PR up soon

**Comment by DanPurdy** [comment]
HI @petetnt, nice one!

Will add it now.

Thanks

**Comment by petetnt** [comment]
:+1: Awesome. Thanks for the great linter!

**Comment by DanPurdy** [comment]
No problem! Hopefully I'll get some time to work on it further soon!
