### ISSUE TITLE
Lint as you type (Atom)

### ISSUE THREAD

**Issue by zslabs** [sasstools/sass-lint#474]
Right now, this linter does not lint as I type; it only lints after a save. This is different than how most other Atom Linters work. I'm not seeing a setting for this behavior; is this intended? Thanks.

**Comment by DanPurdy** [comment]
Hi @zslabs You'll need to open this issue over with linter-sass-lint itself you can find it [here](https://github.com/AtomLinter/linter-sass-lint) This is the repo for sass-lint itself.

We can talk about it there (Im the developer of `linter-sass-lint` for atom)

**Comment by zslabs** [comment]
Gotcha thanks @DanPurdy
