### ISSUE TITLE
Getting error using variables

### ISSUE THREAD

**Issue by mattwoodnyc** [sasstools/sass-lint#475]
I'm getting a parsing error:
```Error: Parsing error at XXX: Please check validity of the block starting from line #5```

line 5:
```right: calc( 100% - (#{$roomListWidth} + #{$panelBWidth}))```

(using sass-lint@1.4.0)

**Comment by DanPurdy** [comment]
Yeah I'm afraid this is due to the AST we are using, it currently doesn't handle interpolation very well. 
There's a few other issues open here to describe this a bit better probably best to start with #44 I'll close this issue just so we keep all the talk in the same place..

**Comment by mattwoodnyc** [comment]
Thanks
