### ISSUE TITLE
CLI should return an error when the styleguides are not met

### ISSUE THREAD

**Issue by queicherius** [sasstools/sass-lint#477]
Right now the CLI doesn't return an error code when the styleguides are not met. That makes it hard using it in projects with `npm test` (e.g. like this: `standard && scss-lint && node tests.js`) to enforce the styleguides.

**Comment by DanPurdy** [comment]
Hi @queicherius I've got a PR in to get this sorted at the moment. It's not as in depth as I would like it to be right now but it should at least send the correct error codes (only 1 and 0) from the CLI.

See #458

Also there's a previous issue regarding error codes so I'll close this issue and keep everything in there. See #221 

Thanks
