### ISSUE TITLE
Ignore node_modules from CLI.

### ISSUE THREAD

**Issue by msecret** [sasstools/sass-lint#478]
I have the following in `.scss-lint.yml`:

```
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore: 
    - 'node_modules/**/*'
```

I'm running scss-lint as an npm script in package.json:

```
"lint": "scss-lint -c .scss-lint.yml",
```

When I run `npm run lint` I still get errors from files within node_modules:

```
node_modules/uswds/assets/_scss/lib/neat/settings/_visual-grid.scss:1 [W] StringQuotes: Prefer single quoted strings
node_modules/uswds/assets/_scss/lib/neat/settings/_visual-grid.scss:25 [W] LeadingZero: `0.4` should be written without a leading zero as `.4`
node_modules/uswds/assets/css/main.scss:7 [E] Syntax Error: Invalid CSS after "@import 'all'": expected "{", was ";"
node_modules/uswds/assets/css/styleguide.scss:6 [E] Syntax Error: Invalid CSS after "@import 'all'": expected "{", was ";"
```

I'm not totally sure if it's picking up my config correctly or not, that could be the issue.

**Comment by DanPurdy** [comment]
This is sass-lint not scss-lint. Two completely different projects. We are node based, scss-lint is ruby based.. Their config file will not work with our package and vice versa.. Did you mean to file this with them?
