### ISSUE TITLE
Write results to file

### ISSUE THREAD

**Issue by davetgreen** [sasstools/sass-lint#48]
One of the features of SCSS Lint that I found useful was the ability to have the results written to a file, with the ability to specify the file path. This would be a really useful addition.

I think it would be useful to silence the console output if writing to a file is chosen.

**Comment by Snugug** [comment]
The way Sass Lint is set up, there is no logging of output. Results are passed to the `format` function to format them for logging, but each implementation chooses their own way of handling output.

The actual output of linting is simply an array of detects. The formatter function is what creates turns the array in to usable output. Currently, it uses ESLint's Stylish formatter, but [any of those formatters](https://github.com/eslint/eslint/tree/master/lib/formatters) could be used in theory.

The question that needs to be discussed is how to best describe what the output file should be and what formatter to use, especially in config.

**Comment by joshuacc** [comment]
I would love to have this as well, particularly with junit or checkstyle XML output so I can easily integrate sass-lint into my continuous integration server.

**Comment by Snugug** [comment]
- [ ] Write output to file
- [ ] Config formatter options
