### ISSUE TITLE
Enhancement: Bang whitespace rules should consider !default flag

### ISSUE THREAD

**Issue by bgriffith** [sasstools/sass-lint#53]
Currently the Space Before Bang and Space After Bang rules only consider the `!important` flag. It should consider the `!default` flag too.

**Comment by Snugug** [comment]
And !global

**Comment by bgriffith** [comment]
Got default flags working fine, but as soon as I use a global flag I get a parse error:

```
Parsing error at /Users/ben/workspace/sass-lint/tests/sass/space-after-bang.scss: Please check validity of the block starting from line #32
  Error: Parsing error at tests/sass/space-after-bang.scss: Please check validity of the block starting from line #32
      at module.exports (lib/groot.js:21:11)
      at Function.sassLint.lintText (index.js:23:13)
      at index.js:73:21
      at Array.forEach (native)
      at Function.sassLint.lintFiles (index.js:72:9)
      at lintFile (tests/main.js:10:22)
      at Context.<anonymous> (tests/main.js:297:5)
```
<img width="263" alt="screen shot 2015-08-31 at 00 16 38" src="https://cloud.githubusercontent.com/assets/2854338/9570044/9a2090c2-4f75-11e5-933d-72635d5b43b1.png">

**Comment by Snugug** [comment]
I think we may need to wait until the next version of Gonzales is released to fully support !global

**Comment by bgriffith** [comment]
Yeah I came to the same conclusion. I'll create a PR for the defaults.

**Comment by JohnAlbin** [comment]
So the linter fails when it sees `!global`? I'm going to open a new issue to track that critical bug. I want to use sass-lint, but can't while that bug is unfixed.
