### ISSUE TITLE
border-zero rule doesn't include border-radius

### ISSUE THREAD

**Issue by Donaldini** [sasstools/sass-lint#534]
I would like to have border-radius included in the border-zero rule.

![screen shot 2016-02-17 at 15 28 24](https://cloud.githubusercontent.com/assets/2185680/13112500/338edd36-d58b-11e5-8c66-33b42c520b1c.png)

It would make sense that the border-zero rule checks for all border-xxx properties.

If it would seem my logic doesn't make sense in a greater scheme, I would love to hear your input :-)

**Comment by alfaproject** [comment]
`border-radius: none` is invalid CSS tho

**Comment by Donaldini** [comment]
Exactly why I thought it would make sense to include it :-)

**Comment by bgriffith** [comment]
`border-zero` rule can be used to enforce using either `0` or `none` so I'm view this isn't compatible with the `border-radius` property (as it would produce invalid css as pointed out by @alfaproject) when the rule value was set to `none`.

I also don't feel we should be checking for invalid css in a rule like this. It would make more sense to have a general invalid-css rule.

**Comment by Donaldini** [comment]
That could also be a good way to snuff out these issues @bgriffith !

Is there some documentation on how to create custom rules, cause I can't seem to find any here?

**Comment by DanPurdy** [comment]
We don't support custom rules at the moment. It's in the pipeline for v2 though which will hopefully be getting under way soon.

**Comment by Donaldini** [comment]
Nice, i'll have to subscribe in a way to be notified of the updates then ;-)

**Comment by DanPurdy** [comment]
Closing this due to it being invalid anyway. But with pluggable rules planned if support is wanted it can be added.
