### ISSUE TITLE
Cannot disable rules inline

### ISSUE THREAD

**Issue by marlowpayne** [sasstools/sass-lint#544]
Maybe I couldn't find it, but I would love an inline rule disable feature, akin to [SCSS-lint](https://github.com/brigade/scss-lint#disabling-linters-via-source).

Even just a general inline disable like:
```
// sass-lint:disable
...
// sass-lint:enable
```

EDIT: Forgot to add:
Running `grunt-sass-lint` v0.1.0, `sass-lint` v1.5.0

**Comment by BPScott** [comment]
Yep, There's already an open ticket for it: #70 and a PR that contains work in progress: #402.

**Comment by marlowpayne** [comment]
Ah, thanks @BPScott. My search skills are obviously terrible :) Closing this duplicate.
