### ISSUE TITLE
Error: Sass-lint filed: missing path

### ISSUE THREAD

**Issue by camielm** [sasstools/sass-lint#545]
Hello,

I can't get sass-lint to work..
In my Sublime document on line 1 it returns: Error: Sass-lint filed: missing path
I tried adding the path /usr/local/bin/sass-lint to my SublimeLinter settings but same result.

Any idea how to solve this?

**Comment by DanPurdy** [comment]
It sounds like your issue is with the [sublime sass lint plugin](https://github.com/skovhus/SublimeLinter-contrib-sass-lint) you may want to file an issue over there

**Comment by camielm** [comment]
Thanks, I will.
