### ISSUE TITLE
Disallow usage of certain properties

### ISSUE THREAD

**Issue by alexeibs** [sasstools/sass-lint#546]
According to this
https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertyspelling
scss-lint supports such a feature. There is a similar linter 'no-misspelled-properties' in sass-lint but its config can include only 'extra_properties'.
What do you think about extending functionality of 'no-misspelled-properties' to support 'disabled_properties' too? Source code of this linter looks pretty simple so creating a pull request wouldn't be difficult.

**Comment by DanPurdy** [comment]
We favour small single purpose rules so we would probably prefer a completely separate rule for this as checking the spelling of a property and also disallowing properties is technically two different use cases. Something like `no-disallowed-properties` would be ok.

**Comment by Snugug** [comment]
We prefer single targeted rules as much as possible, so we'd prefer a separate rule disallowing properties to an option on misspelled rules. That being said, I think that's fine, I'd be open to adding that rule.
