### ISSUE TITLE
How to ingore duplicate property

### ISSUE THREAD

**Issue by aseem2625** [sasstools/sass-lint#547]
I was display property as duplicate at one place.

Written as in sass-lint config. It's a YAML format.

```  no-duplicate-properties:
    - 2
    - ignore: display
```
But didn't work. Can someone please help.

Also, can anyone give pointers to thread saying when the per-line wise lint ignore will come just like es-lint.

Thanks

**Comment by DanPurdy** [comment]
Have you looked at the docs?

https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-duplicate-properties.md

It shows an example of the exclude setting

**Comment by bgriffith** [comment]
```
no-duplicate-properties:
    - 2
    -
      ignore: 
        - display
```

**Comment by aseem2625** [comment]
```
no-duplicate-properties:
    - 2
    - exclude: 
        - display
```

Thanks. Worked. I should take care to see the docs again.
