### ISSUE TITLE
Add background-attachment to SMACSS property sort order

### ISSUE THREAD

**Issue by mdmoreau** [sasstools/sass-lint#548]
Would you be interested in a PR for adding this property?  Noticed it missing on a recent project, and it looks like scss-lint added it in a little while back with https://github.com/brigade/scss-lint/commit/7358b726f7929bcccebfb43400ffa281a474555a.

**Comment by DanPurdy** [comment]
Yeah sure, thanks

**Comment by mdmoreau** [comment]
Looks like they added some transform/transition ones as well - want those too?  https://github.com/brigade/scss-lint/commit/a0465589d15ac35ec54d340e40642e898cd50d40

**Comment by bgriffith** [comment]
Happy to add anything that's missing :+1:
