### ISSUE TITLE
Install Issue: lodash - node version

### ISSUE THREAD

**Issue by maxcbc** [sasstools/sass-lint#549]
Hi all,
I'm getting the following issue trying to install sass-lint.

```
No compatible version found: lodash.upperfirst@^3.0.0
npm ERR! Valid install targets:
npm ERR! 4.1.2, 4.1.1, 4.1.0, 4.0.2, 4.0.1, 4.0.0

```
I'm running node 4.3.1 and npm 3.75. 

I assume this means that lodash.upperfirst 3.0.0 doesn't support the version of node I'm running, is there anyway round this, other than downgrading my node version (which I don't want to do).

Best,
Max

**Comment by DanPurdy** [comment]
Hi @maxcbc it looks like lodash have unpublished all version previous to v4 from npm which obviously is breaking a LOT of packages around the web at the moment.

See here https://github.com/lodash/lodash/issues/2059

I'll see if we can update our version but hopefully lodash themselves will rectify this soon..

**Comment by bgriffith** [comment]
Hot fixing now....

**Comment by maxcbc** [comment]
Thanks chaps, 
Much obliged. One of the most fastest responses I've ever had. Top marks fellas.

**Comment by DanPurdy** [comment]
Ok sass-lint is updated to 1.5.1 and this should be resolved for now.

**Comment by ACOSW** [comment]
@DanPurdy installs fine now. Thanks!
