### ISSUE TITLE
Force leading zero?

### ISSUE THREAD

**Issue by dustindowell22** [sasstools/sass-lint#558]
Just like the title says.

I have a script to remove these after compiling but I think it reads better while writing. Just my personal preference and I'd like to keep everything consistent.

Setting `leading-zero: 0` just removes the rule instead of forcing a leading zero.

**Comment by erikdesjardins** [comment]
See https://github.com/sasstools/sass-lint/blob/develop/docs/rules/leading-zero.md

Rule configuration is explained here: https://github.com/sasstools/sass-lint#rules

You need to set `include: true` in the rule options, like this:

```yml
leading-zero:
  - 2
  -
    include: true
```

**Comment by dustindowell22** [comment]
That does it thanks.
