### ISSUE TITLE
Add maxWarnings cli option

### ISSUE THREAD

**Issue by house9** [sasstools/sass-lint#567]
Add `--max-warnings` cli option similar to [eslint](http://eslint.org/docs/user-guide/command-line-interface#options)

Exit with non-zero value when the number of warnings is greater than the `maxWarning` option

Easily allows failing CI builds without needing to override the default rules by specifying the `2` value for every one

**Comment by DanPurdy** [comment]
Believe it or not I was actually looking at adding this very soon. Our CLI is going to get a lot of attention once 1.6 is out I think.

**Comment by house9** [comment]
Awesome! I went ahead and added it last night, I'll send over a PR for review
