### ISSUE TITLE
Sample sass-lint.yml should contain explicit examples

### ISSUE THREAD

**Issue by lozandier** [sasstools/sass-lint#57]
The readme shows rules with configuration options be set in example like the following code snippet, but does not does so in the sample `.sass-lint.yml`:

```
indentation:
  - 2
  -
    size: 2
```

It seems reasonable that rules such as `quotes` and `indentation`—rules commonly needed to be configured explicitly through options be done in the `.sass-lint.yml` file to reinforce this being done.

Noticed  devs less experienced with YAML files & `sass-lint` I know were confused when they were getting output such as the following screenshot with their attempts of using `gulp-sass-lint` for the first time I've emulated:

![screen shot 2015-08-30 at 9 58 47 pm](https://cloud.githubusercontent.com/assets/1223224/9570858/a9a530ec-4f62-11e5-8d76-0ad36f4465fa.png)

**Comment by Snugug** [comment]
We can improve the documentation to include a proper sample config file instead of pointing to our defaults, but I'm not going to add explicit configuration to the defaults as I want to ensure that that is defined in each rule.

**Comment by lozandier** [comment]
That's understandable.
