### ISSUE TITLE
sass-lint: command not found

### ISSUE THREAD

**Issue by asaadmahmoodspin** [sasstools/sass-lint#570]
I've installed sass-lint through:
`npm install sass-lint --save-dev` in my project and globally `sudo npm install -g sass-lint`
The sass-lint folder is placed inside my /node_modules folder, However if I do sass-lint on terminal, I get:
`-bash: sass-lint: command not found`.

**Comment by DanPurdy** [comment]
You shouldn't have to use sudo with NPM. That installs it as your root user. You need to npm install without sudo. If you can't then you have permission issues that will need to be resolved. see [here](https://docs.npmjs.com/getting-started/fixing-npm-permissions) If it's not in your $PATH then the command will remain unknown. if you do `npm get prefix` you will see your global NPM path you can then go to that folder and look in `lib/node_modules` and see if sass-lint is there or in `bin` to see if it is symlinked anywhere.

Once your permissions etc are done just try `npm install sass-lint -g` and then run `sass-lint` in your projects root directory.

You don't need sass-lint installed in your project either to be able to use the global version of it. You can use the local one in conjunction with npm scripts or gulp/grunt for example.

Hope that helps

**Comment by asaadmahmoodspin** [comment]
Did that, I can see sass-lint symlinked inside the `bin` folder. And there weren't no permission issues but I did sudo because the normal npm wasn't working. I did `npm install sass-lint -g` again and still `sass-lint` is not working.

**Comment by DanPurdy** [comment]
so that folder must not be in your $PATH then

**Comment by asaadmahmoodspin** [comment]
If i do `npm get prefix` I get: `/usr/local/Cellar/node/0.10.32`
Should I add it to my .bash_profile like:
```
PATH="/usr/local/Cellar/node/0.10.32"
export PATH
```
?

**Comment by DanPurdy** [comment]
`PATH="$PATH:/usr/local/Cellar/node/0.10.32"` should cover it

then do `. ~/.bash_profile`

**Comment by DanPurdy** [comment]
Sorry i updated the above, try it again.

**Comment by asaadmahmoodspin** [comment]
Did that, this is part of my bash profile.
And if I do I get:
```
`@PATH=/usr/local/Cellar/node/0.10.32/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/go/bin:/usr/local/go/bin:/Users/asaadmahmood/.rvm/bin:/usr/local/go/bin': not a valid identifier

```
![screen shot 2016-03-15 at 10 14 57 pm](https://cloud.githubusercontent.com/assets/11034289/13787197/cb4f0c14-eafc-11e5-8e2c-985343cfacdc.png)

**Comment by asaadmahmoodspin** [comment]
Okay, something worked, but now I get this.
![screen shot 2016-03-15 at 10 28 00 pm](https://cloud.githubusercontent.com/assets/11034289/13787287/31cfdffe-eafd-11e5-900c-2fa7bbda0c28.png)

**Comment by DanPurdy** [comment]
Have you got a .sass-lint.yml config file in the root of your project?

**Comment by asaadmahmoodspin** [comment]
Yes. I copied the default file here: `https://raw.githubusercontent.com/sasstools/sass-lint/master/lib/config/sass-lint.yml`

**Comment by DanPurdy** [comment]
And you put a dot in front of the file name? Are you running sass-lint from inside that project folder?

**Comment by asaadmahmoodspin** [comment]
I've got the sass-lint sublime plugin, it says sass-lint failed, missing path.
I didn't add the dot before but I added it, now it's like `.sass-lint.yml` and if I do a sass-lint from inside the project root I still get that missing path.

**Comment by asaadmahmoodspin** [comment]
Even though I still get the missing path error in terminal, It gives me another error now in sublime text.
![screen shot 2016-03-15 at 10 44 44 pm](https://cloud.githubusercontent.com/assets/11034289/13787899/a6cb064c-eaff-11e5-9556-f36e4385e10b.png)

**Comment by DanPurdy** [comment]
We don't support the sublime plugin you'll need to ask about that in its respective repo. 

I though you were trying to get the Cli working? You have sass files in the project already? Have your tried running it with the -v flag to stop lint errors dumping you out?

**Comment by asaadmahmoodspin** [comment]
Sure, I'm sorry for going off track and yeah for starters it was to get the CLI working. And yes I do have .scss files in the project. Is it fine even if I get the missing path error when I do `sass-lint` in my root folder? One thing to note is that my sass files however are not directly at the root folder, they're in `web/sass-files`

**Comment by DanPurdy** [comment]
The error you're seeing in sublime though is a parse error with the AST, out of interest what is the code at line 3 of that file?

**Comment by asaadmahmoodspin** [comment]
![screen shot 2016-03-15 at 10 50 26 pm](https://cloud.githubusercontent.com/assets/11034289/13788089/558aafc0-eb00-11e5-90f7-88d41a58fc11.png)

**Comment by DanPurdy** [comment]
That's fine because if you look in your config file it should be including them in a glob pattern.. Basically go into your project root do sass-lint -v and see if you get the error

**Comment by DanPurdy** [comment]
Sorry I'm on a train so my replies are going out of sync

**Comment by asaadmahmoodspin** [comment]
No worries, I'm thankful for all the help you've given. Really appreciated.

**Comment by asaadmahmoodspin** [comment]
![screen shot 2016-03-15 at 10 52 35 pm](https://cloud.githubusercontent.com/assets/11034289/13788185/a21f8dce-eb00-11e5-8e19-d67bf6ba73ca.png)

**Comment by DanPurdy** [comment]
So your project is called platform? Try doing `sass-lint -v -c .sass-lint.yml` same error?

**Comment by asaadmahmoodspin** [comment]
Yes.

**Comment by asaadmahmoodspin** [comment]
![screen shot 2016-03-15 at 10 58 03 pm](https://cloud.githubusercontent.com/assets/11034289/13788398/64030290-eb01-11e5-821f-5c956766f616.png)

**Comment by asaadmahmoodspin** [comment]
Okay I followed it from here and that's all It seems to be working with `sass-lint --no-exit --verbose`.
https://github.com/sasstools/sass-lint/issues/563

**Comment by asaadmahmoodspin** [comment]
Thanks a lot @DanPurdy

**Comment by DanPurdy** [comment]
No problem, glad you got it sorted

**Comment by asaadmahmoodspin** [comment]
Hey @DanPurdy I get this error in sublime. I think it maybe linked to what I get if I do sass-lint. Any ideas?
![screen shot 2016-03-17 at 1 36 07 pm](https://cloud.githubusercontent.com/assets/11034289/13840616/5d7d5dae-ec45-11e5-94ab-a76000f333ce.png)
![4286bb42-eb8e-11e5-8a1b-948e9e86fc07](https://cloud.githubusercontent.com/assets/11034289/13840617/5eb0ba22-ec45-11e5-8538-08547c210e54.png)

**Comment by asaadmahmoodspin** [comment]
The error I get is, please check the validity of block etc. If it's not linked to assert.js issue let me know.

**Comment by DanPurdy** [comment]
It's an issue with the AST, that we're using.. It doesn't support interpolation. The latest version and our 1.6 update do support it but we cant release it until the AST gonzales-pe removes it's bash specific post install scripts.. There are already lots of issues around this open so I'll close this again but you can track the gonzales 3.2 update Pr that we have open to be notified when support is likely to come out, I would hope very very soon!

**Comment by asaadmahmoodspin** [comment]
Cool, thanks.
