### ISSUE TITLE
Missing `SelectorDepth` rules?

### ISSUE THREAD

**Issue by s10wen** [sasstools/sass-lint#574]
I noticed some `SelectorDepth` warnings, but I couldn't find the rules: https://github.com/sasstools/sass-lint/tree/develop/docs/rules

Wondering if they need to be added?

**Comment by DanPurdy** [comment]
Do you mean our `nesting-depth` rule? https://github.com/sasstools/sass-lint/blob/develop/docs/rules/nesting-depth.md

**Comment by s10wen** [comment]
Hey @DanPurdy thanks for the reply, I'm finding it tricky to drill down the warning to the corresponding rule in some cases. Would it be helpful to have a list of the warnings on the `rule.md` for easier searchability? e.g. can't find anything for `ElsePlacement` either: https://github.com/sasstools/sass-lint/search?utf8=%E2%9C%93&q=ElsePlacement

**Comment by DanPurdy** [comment]
No problem, Are you sure you're in the right repo? They look like `scss-lint` rules to me.. 

`scss-lint` is a linter for only scss files running in ruby
`sass-lint` is a linter for scss/Sass files runing on node


You're probably trying to find [this](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#elseplacement) and [this](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#selectordepth)

**Comment by s10wen** [comment]
@DanPurdy Ahhhhhhhhhhhhhhhhhhhh, sorry! I am indeed, thanks very much.
