### ISSUE TITLE
SASS-syntax linter with unexpected warning

### ISSUE THREAD

**Issue by nuflowx** [sasstools/sass-lint#579]
For some reason I get a lot of warnings in my file when using `.sass`. Trying the same with `.scss` has no problems.

Here are a few examples I am getting:

![new-line-lint](https://cloud.githubusercontent.com/assets/17532211/14059747/bf4de746-f344-11e5-913e-581b92e8aa3e.png)
![lint-warning-1](https://cloud.githubusercontent.com/assets/17532211/14059770/c97816be-f345-11e5-9960-175d512bd630.png)
![lint-warning-2](https://cloud.githubusercontent.com/assets/17532211/14059771/cd5d7f6c-f345-11e5-9d65-cc41cc9925dd.png)
![lint-warning-3](https://cloud.githubusercontent.com/assets/17532211/14059772/cf7b5d28-f345-11e5-98b7-e6b8625892c6.png)

I deactivated some rules for now so I don't get the warnings any more

**Comment by DanPurdy** [comment]
The AST we're using has a few Sass issues that we're hoping to have ironed out soon. Sass unfortunately has a few issues that some of our rules don't manage to get around. If you could post the file that all these are occurring in it would help us in future to add extra tests to our rules.

Thanks

**Comment by DanPurdy** [comment]
The only issue I can still see remaining in the above examples are to do with the indentation rule which we have open issues to fix and will be looking into very shortly now that sass-lint 1.6.0 is available.

I'm going to close this in favour of the issues for the specific problems but thank you for raising these.

**Comment by nuflowx** [comment]
Wow, great to hear about the 1.6.0 release. Checking it out right away! thanks for all the work :)

**Comment by nuflowx** [comment]
I'm still seeing the 'Final line must end with a new line' error, although that is present. The rest (except indentation) seems to be fixed with this release :)

**Comment by bgriffith** [comment]
@nuflowx The `final-newline` rule will hopefully be looked at over the next couple of days so stay tuned.
