### ISSUE TITLE
Rules explicitly turned off if not listed ESLint style

### ISSUE THREAD

**Issue by lozandier** [sasstools/sass-lint#58]
It's not clear if rules *not* present in `sass-lint.yml` files are turned off automatically (ESLint 1.0 style) or not. 

With early runs of `gulp-sass-lint`, that does not seem to be the case; for codebases that have both `Sass` & `SCSS` litn files, it seems there's issues propagating from `gonzales-pe` unless `trailing-semicolon` is explicitly set to `0` rather than merely omitting the rule altogether:

![screen shot 2015-08-30 at 10 15 14 pm](https://cloud.githubusercontent.com/assets/1223224/9570985/bc366fee-4f64-11e5-98a7-43afe6a162d1.png)

Seemingly any rule not listing in the `sass-lint.yml` should be turned off (severity of `0`)  since that's the clearest way for users of the plugin-in to communicate they are not concerned of that rule being applied to their codebase.

Overtime, it can be more work for them to apply rules they don't care about in their codebase than the rules they care about as rules become simultaneously more useful & complex.

**Comment by Snugug** [comment]
I originally had it so that user config overrode the default configuration instead of merging, but found that if someone only wanted to change indentation, for instance, they needed to be explicit with their whole configuration.

One option is to not have anything configured by default.

**Comment by lozandier** [comment]
That sounds very sensical to me actually; for the ESLint-style behavior, perhaps it's a flag?
