### ISSUE TITLE
Unexpected parse error in file

### ISSUE THREAD

**Issue by nuflowx** [sasstools/sass-lint#580]
sass-lint-version: 1.5.1

I am using the `.sass`-syntax and am getting

![Unexpected parse error in file](https://cloud.githubusercontent.com/assets/17532211/14059987/d3b6c6f0-f34c-11e5-999c-81f101da54bc.png)

at the top of most of my files. I couldn't find any documentation what this means. My code is fine btw.

**Comment by DanPurdy** [comment]
These parse errors are to do with the AST we use, gonzales-pe being unable to parse your code for some reason. Our 1.6 update is coming soon to hopefully solve a lot of these issues but if you'd like to check that the update will help you in your situation you could copy and paste your code in to the following tool http://tonyganch.com/gonzales-pe/

**Comment by nuflowx** [comment]
Thanks Dan!

The link you provided gave me a lot of `undefined`-statements back with the `fallback to primitives`, but only with the `sass`-syntax. The `current dev` handels everything as it should. So it seems that the 1.6 will solve these issues :tada: .

**Comment by DanPurdy** [comment]
Awesome, thats good news. Thanks for taking the time to check. :+1:

**Comment by rbaprado** [comment]
I am facing this problem here as well, version 1.10.2

**Comment by DanPurdy** [comment]
@rbaprado can you open a separate issue please. Although it's the same error it's a different issue.

Thanks

**Comment by rbaprado** [comment]
Done: #969
