### ISSUE TITLE
Any line separator other than CR breaks more than one rules when using tabs

### ISSUE THREAD

**Issue by vmasto** [sasstools/sass-lint#595]
Hi guys, I know this is a known issue, I would like to report a couple more use cases that break:

- Indentation rules do not work correctly and fail to report
- `empty-line-between-blocks` gives false positives at every single rule

Along with basically not being able to even run while being in anything other than CR when using tabs, this makes the module unusable.

I was wondering if there was any progress to fixing this (updating the AST module?). There are many people that have to use tabs and it's unfortunate that we're not able to use the only Sass/SCSS linter available without having to use ruby.

**Comment by DanPurdy** [comment]
Unfortunately yes, we know your frustration, we're limited to the support that Gonzales-pe has though which at the moment has a few issues with non LF line endings. There are open issues on the gonzales repo and we're about to release an update to sass-lint that uses the latest gonzales (once we've investigated some windows/Sass issues) but the core problem remains unresolved.

As for updating the AST, we're currently looking at using a fork i've prepared to make it so gonzales is at least installable on a windows / non bash machine there's the option to look into it and update it but it's a considerable time investment that unfortunately we dont have. A few PR's that fix certain issues with gonzales also remain un merged so we're kind of stuck between a rock and a hard place at the moment...

If yourself or anyone else would like to get involved with updating the AST then please do. Thanks :+1:

**Comment by vmasto** [comment]
Thanks for the reply Dan. 

BTW, my issues are all while using LF, I'm on OSX.

LF + Tabs = everything breaks (errors out completely)
CR + Tabs = most rules work, except for indentation and spacing.

If I use spaces everything seems to be working correctly, but I can't use spaces I'm afraid.

**Comment by DanPurdy** [comment]
Hi @vmasto Would you mind trying this again with the latest release of sass-lint (1.6.0) Tab support and CRLF support should now be available. 

The indentation rule may still be throwing some odd lint warnings but i believe all of the other oddities with the combinations you mentioned above should be solved.

We're also now running all our with LF and CRLF line endings and will be looking to add tabs to that mix shortly. 

Either way would be good to hear back if a lot of your issues are solved 👍 thanks.

**Comment by vmasto** [comment]
Heya, thanks a lot for the update.

It doesn't seem to crash now but yeap the `indentation` and `mixed tabs and spaces` throw on every line (without actually having errors ofc, using tabs + LF), but it's great progress, thanks for looking at this! Eager to be able to fully use tabs soon 😃

**Comment by DanPurdy** [comment]
Awesome, I'll close this issue for now then as we're tracking indentation issues with tabs elsewhere. Thanks for letting us know. 👍
