### ISSUE TITLE
Trailing whitespace rule

### ISSUE THREAD

**Issue by gyoshev** [sasstools/sass-lint#596]
I couldn't find a rule that prohibits trailing whitespace at the end of a line:

    .foo {\s\s\s
        color: red;\s\s
    }

Is there such a rule, and if not, does it make sense in the context of sass-lint?

**Comment by chielkunkels** [comment]
There is also the `final-newline` rule, which kinda fits in the same street in my opinion - so I definitely think it makes sense. The question is of course if the AST supports it.

**Comment by gyoshev** [comment]
[Turns out it does](https://github.com/gyoshev/sass-lint/blob/feature/no-trailing-whitespace-rule/lib/rules/no-trailing-whitespace.js)! Traversing `'space'` nodes is enough for SCSS, they contain the trailing whitespace and the newline. For SASS nodes, it is more tricky, as the newline is parsed as a `declarationDelimeter`. Accumulating the found whitespace addresses that.

**Comment by DanPurdy** [comment]
@gyoshev Nice, if you want to get some tests etc for that we'd be happy for you to do a pull request.

`Sass` format is definitely the problem child at the moment with the AST as it is.

**Comment by DanPurdy** [comment]
hmm ignore my previous comment, I see you've already submitted one! :+1:
