### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by xzyfer** [sasstools/sass-lint#6]
This issue will track the progress of the 1.0.0 release

### 1st Level Features

Features that must be launched with

- [x] YAML config (partially complete)
- [x] Work on globs/file paths as well as data streams
- [x] [Gulp plugin](https://github.com/sasstools/gulp-sass-lint)
- [x] [Grunt Plugin](https://github.com/sasstools/grunt-sass-lint/)

~~Pluggable rules~~

### 2nd Level Features

Features that would be nice to have for initial release, but not blockers

- [x] `.sass` support (dependent upon [scssparse](https://github.com/sasstools/scssparse) or other AST parser **Gonzales**)

~~CLI (being able to integrate with other tools higher priority)~~
~~Plugin compatibility with ESLint plugins (dependent upon `scssparse` AST)~~

<h3 id="rules">Rules</h3>

These are the rules we're aiming to support for 1.0.0 as per the discussion in https://github.com/Snugug/sass-lint/issues/3#issuecomment-91764822. [Reference](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md)

- [x] Extends before Mixins
- [x] Extends before Declarations
- [x] Mixins before Declarations
- [x] EmptyLineBetweenBlocks
- [x] EmptyRule
- [x] FinalNewline
- [x] IdSelector
- [x] Indentation
- [x] LeadingZero
- [x] NestingDepth
- [x] PlaceholderInExtend
- [x] PropertySortOrder
- [x] SelectorDepth
- [x] SingleLinePerProperty
- [x] SingleLinePerSelector
- [x] SpaceAfterComma
- [x] SpaceAfterPropertyColon
- [x] SpaceAfterPropertyName
- [x] SpaceBetweenParens
- [x] SpaceBeforeBrace
- [x] TrailingSemicolon

**Comment by benhinchley** [comment]
This comment is not related at all but I am really glad I stumbled across this project, as I just started the boilerplate for the same thing. I am glad that someone else thought of this as well. Will try help out where I can

**Comment by aarr0n** [comment]
How is this release tracking? Is there an initial release date?

**Comment by xzyfer** [comment]
Rest assured this is still under active development. We're working on the underlying tooling at the moment. I'm holidays trying to crank this out :)

**Comment by aarr0n** [comment]
Awesome :shipit: !

**Comment by bgriffith** [comment]
Just to add that that is great news! Really looking forward to this. Thanks for all the hard work :+1:

**Comment by mischkl** [comment]
I wonder if it might be possible to start porting some of the existing scss-lint linters by compiling Ruby to JavaScript using https://github.com/opal/opal? Just a pie-in-the-sky naive idea, but maybe it's worth a shot?

Then again using the ESLint plugin system sounds like a good idea too. :)

**Comment by Maximilianos** [comment]
Looking forward to this greatly! :+1: :shipit:

**Comment by Turqueso** [comment]
:+1: :shipit:

**Comment by xzyfer** [comment]
Apologies for the radio silence. Work is still happening here. I'm currently a bit bogged down with an upcoming LibSass release but this is happening!

**Comment by matthewrose** [comment]
Thanks for the update! I'm sure I speak for the larger libSass community when I say we are REALLY looking forward to this. As far as I can tell there is still not a  Ruby-free system for linting Sass at build-time so I'm very excited about this project.

**Comment by Snugug** [comment]
## Update

We will have a 0.x release before a full 1.x release. That release will not include the following:

* CLI
* Pluggable Rules (although the groundwork is being laid to allow for them)
* ESLint Compatibility (we're releasing with Gomez, so no compatibility. Closer to CSS Comb)
* A subset of the above rules, with the hope of allowing individuals to start contributing their own

**Comment by ArmorDarks** [comment]
Looking forward to test it! Thanks for great work!

**Comment by Razenbull** [comment]
First of all thanks for your work, this looks awesome. I just wonder if it will be also pluggable to a Grunt project?

**Comment by Snugug** [comment]
@Razenbull I don't use Grunt so I would be uncomfortable maintaining a plugin for it, but it's possible to plug it in. If someone would like to write a Grunt plugin for it, though, go for it!

**Comment by Snugug** [comment]
All done for the things we're tracking here! Just cleanup and proper tests left to write!
