### ISSUE TITLE
custom file extensions: cannot read poperty 'toString' of undefined

### ISSUE THREAD

**Issue by maddrag0n** [sasstools/sass-lint#609]
I have set `include: '**/*.s+(a|c)ss?(hbs)'` to enable linting for .scsshbs files, which get handled differently  in my build setup (they are converted to native handlebars functions).

When I open the file in Atom, it only shows a single error: `Cannot read poperty 'toString' of undefined`.

Am I holding it wrong? Or do I have to add a comment to the file to indicate whether it’s Sass or SCSS?

**Comment by DanPurdy** [comment]
Try adding the syntax to your config file and see if that helps. Internally sass-lint is only working with sass and scss extensions but a recent addition was to specify which syntax to use so this may help you.

in your config file do the following for scss

```
# Linter Options
options:
  syntax: 'scss'
```

change it to `'sass'` if you use that format.

Let us know if there's an issue with that.

**Comment by maddrag0n** [comment]
sadly the error remains the same. I am on OS X, running Atom 1.6.2 with linter-sass-lint 1.3.1, linter 1.11.4

**Comment by DanPurdy** [comment]
Hmm, ok i'll have a look into it.

**Comment by DanPurdy** [comment]
Hi @maddrag0n So I just released v1.5.0 of `linter-sass-lint` for atom which includes a fix for this. It should now check the complete file extension and look for a instance of `scss` or `sass` and then attempt to lint with that syntax set. I'll close this now as I've tested it with a hbs file, but please be aware if you use any non standard SCSS or Sass code (such as a handlebars block {{ AString }}) within that file a parse error will be thrown as we only support the Sass spec.
