### ISSUE TITLE
Brace style rule 'stroustrup' and multiline mixin parameters

### ISSUE THREAD

**Issue by Igloczek** [sasstools/sass-lint#632]
After upgrade to 1.6.0 (to be honest I don't want to upgrade, but gulp wrapper use version ^1.5.1 - so I'm doomed...) I got many new errors in brace-styles rule.

I'm using 'stroustrup' and now this type of code fails tests:
```scss
 @mixin _suuuper-long-mixin-name(
    $_oversized-paramams-names-was-moved-to-new-line,
    $_because-i-want-to-keep-lines-under-80-chars
) {
    [...]
}
```
IMO it still fit in that rule, but tests checks just if start and end is on same line 😞

**Comment by bgriffith** [comment]
Yeah I agree - appears to be a regression - will look at fixing asap.

**Comment by Igloczek** [comment]
Thank you so much!
