### ISSUE TITLE
SCSS -  Parser breaks on nested child selectors

### ISSUE THREAD

**Issue by colin-marshall** [sasstools/sass-lint#643]
Hey guys, thanks for the awesome work getting 1.6 out! I just tested it out with Foundation and noticed a lot of the files that were throwing fatal errors are now getting linted (yay!), but there's still a couple fatal errors being thrown in a few files. It looks like there are two issues causing six files to fail.

This error is an issue with the AST (tonyganch/gonzales-pe#130), but since you're using a fork and there is a PR open that resolves this issue (tonyganch/gonzales-pe#157), I figured it was worth bringing up here.

These are the breaking lines:
https://github.com/zurb/foundation-sites/blob/develop/scss/components/_dropdown-menu.scss#L68
https://github.com/zurb/foundation-sites/blob/develop/scss/components/_menu.scss#L59
https://github.com/zurb/foundation-sites/blob/develop/scss/components/_tabs.scss#L127

**Comment by bgriffith** [comment]
Thanks for the report. We'll look at getting the fix in the fork :+1:

**Comment by DanPurdy** [comment]
This shouldn't have been closed.. Still seems to break

**Comment by colin-marshall** [comment]
@DanPurdy the breaking lines referenced in OP are no longer breaking with v1.7.0.

**Comment by DanPurdy** [comment]
@colin-marshall great news! I must of been having a moment when i tested this earlier on..

I'll close this for now then, glad it's working!
