### ISSUE TITLE
error in CLI example of ignoring files/patterns

### ISSUE THREAD

**Issue by alxndr** [sasstools/sass-lint#649]
In the ["Ignore files/patterns" section of the Readme](https://github.com/sasstools/sass-lint/blob/6b041473605beb5fffa8bf641f96a22ae481a0e2/README.md#ignore-filespatterns), the short flags example does not ignore the `dist/other.scss` file mentioned in the text.

[Got a fix in this branch](https://github.com/sasstools/sass-lint/compare/develop...alxndr:doc-tweak) (along with some typo fixes).

**Comment by DanPurdy** [comment]
Ah yeah, thanks for catching that, feel free to submit a PR, we'd be happy to merge it in.

**Comment by alxndr** [comment]
thanks, submitted #650

**Comment by DanPurdy** [comment]
fixed in #650
