### ISSUE TITLE
Colons for pseudo-classes and pseudo-elements

### ISSUE THREAD

**Issue by gtramontina** [sasstools/sass-lint#662]
Copied verbatim from https://github.com/brigade/scss-lint/issues/592:

---

CSS3 introduces a distinction between using single or double colons for pseudo-classes and pseudo-elements. Per MDN:

> Sometimes you will see double colons (::) instead of just one (:). This is part of CSS3 and an attempt to distinguish between pseudo-classes and pseudo-elements. Most browsers support both values.

It’d be nice to have a linter to check that:

* Pseudo-**classes** have **one** colon (`:`)
* Pseudo-**elements** have **two** colons (`::`)

---

https://github.com/brigade/scss-lint/pull/634/files

**Comment by bgriffith** [comment]
Thanks for the request. Would be a good rule to have!

**Comment by gtramontina** [comment]
Cool... I'll take a stab at it .... maybe tonight.

**Comment by anpa** [comment]
Thanks for this, this is very useful! But what happened to this rule? I can see that it was merged but it doesn't seem to available.

**Comment by bgriffith** [comment]
It'll be released with version `1.8` (the next release) - so pretty soon.
