### ISSUE TITLE
Support for node 0.10.x

### ISSUE THREAD

**Issue by ianand2** [sasstools/sass-lint#672]
Hi
   There seems to be one usage of path.isAbsolute in lib/config.js which is not allowing this package to be used in node 0.10
https://github.com/sasstools/sass-lint/blob/master/lib/config.js#L82
It can be fixed by using something like path-is-absolute. Let me know if you would like me to send a PR with the change

Thanks

**Comment by DanPurdy** [comment]
Hi @ianand2 a PR would be very welcome. We recently took the decision to no longer 'officially' support 0.10.x but happy to still see fixes for it where necessary.

**Comment by ianand2** [comment]
@DanPurdy sorry for the delay, submitted the PR

**Comment by DanPurdy** [comment]
No problem at all, thanks for contributing!

**Comment by DanPurdy** [comment]
Fixed from #706 will be with you for sass-lint 1.8.0 which should land this week some time.
