### ISSUE TITLE
Class Name Format

### ISSUE THREAD

**Issue by bsteffl** [sasstools/sass-lint#678]
Add support for pascal case to Class Name Format linter.
https://github.com/sasstools/sass-lint/blob/master/docs/rules/class-name-format.md

It would be nice to support a naming convention like [SUIT CSS](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md).

**Comment by DanPurdy** [comment]
Hi @bsteffl thanks for the suggestions, I think we will add Pascal case definitely, as for SUIT css I'm not sure how much use we would see of it but you do have the option of providing your own Regex pattern to this rule and custom warning messages so you can suit it to your needs (unintended pun btw).

There could almost be a separate rule specifically for SUIT CSS as it has a few different naming conventions. That could be another feature request though.

👍
