### ISSUE TITLE
Shared lint config amongst projects

### ISSUE THREAD

**Issue by peduarte** [sasstools/sass-lint#718]
Hey guys,

I tried finding an answer to this question but I couldn't so apologies if this is a duplicate issue.

I've got a few different repos and I'd like them all to share the same Config file, but I'd also like to avoid duplicating the config file for maintainability sake.

My plan was:
1. Create a repo dedicated for `.sass-lint.yml`
2. Publish package to NPM
3. Install package (sass lint config)
4. Point Sass Lint to this config

Steps 1–3 have worked out fine 👌

The issue I am having is with step 4.
I've tried a few different ways, but essentially, this is what I am trying:

Script in *package.json*
```
{
  "scripts": {
    "sass-lint": "sass-lint -c ./.sass-lint.yml './src/**/*.s+(a|c)ss' --verbose --no-exit"
  }
}
```

Local `.sass-lint.yml` in root
```
options:
  config-file: ./node_modules/@private-npm-name/sass-lint-config/.sass-lint.yml
  merge-default-rules: true
```

I would like to be able to use the `config-file` option to point to an external config file and be able to extend it by setting new rules in the local `.sass-lint.yml`. I am currently doing this with eslint, the same concept. 

What's actually happening is that Sass Lint completely ignored the external config.

version of Sass Lint: 1.7.0

Any help will be much appreciated!

**Comment by DanPurdy** [comment]
I'll have a look into it, we haven't officially added support for extending configurations as you can in eslint yet but it's strange that your config file path you specified isn't being read.

**Comment by peduarte** [comment]
Thanks @DanPurdy

**Comment by DanPurdy** [comment]
FYI #140 and #139 are probably relevant here too. I'll take a look at your config declaration and see what is going on later tonight.

**Comment by peduarte** [comment]
Thanks, I'll follow those

**Comment by DanPurdy** [comment]
Ok @peduarte You've uncovered a bug that I'm amazed we haven't been testing for or caught!

It does indeed seem that if you specify a config file within a config file it is ignored! Passing this option through as an option directly to our methods is working fine but we never actually check to see if this property exists in your config. I'm just going to look at how this would/should work when implemented and will have this fixed up and ready soon. Thanks again 👍

**Comment by peduarte** [comment]
No worries! ✌️

**Comment by DanPurdy** [comment]
Hopefully #733 should solve your problem. It allows you to specify config files to extend from within your project config file (as many 'extends' as you like too.).

This will be mainly feature filler into we roll out proper config extends in a similar vein to how eslint does it.

**Comment by peduarte** [comment]
@DanPurdy Sweet man! I'll wait when it's merged and give it a go! Will you let me know when a new version has been published to npm?

**Comment by DanPurdy** [comment]
@peduarte sass-lint 1.8.0 is out now
