### ISSUE TITLE
Property Units documentation citing deprecated naming rule

### ISSUE THREAD

**Issue by adrifmonte** [sasstools/sass-lint#740]
I was looking into every rule documentation, and I found an incorrect naming usage:

https://github.com/sasstools/sass-lint/blob/master/docs/rules/property-units.md

While the options are just `global` and `per-property`, the second example mentions about `globally-allowed-units` and `units-allowed-for-properties`.

I believe those are their former names, which after a rename refactoring, was missed to be updated. Updating them to `global` and `per-property` should fix the issue.

**Comment by DanPurdy** [comment]
Thanks, do you want to submit a PR? We can update it if not. 👍
