### ISSUE TITLE
ParserException: Unexpected input token AMPERSAND

### ISSUE THREAD

**Issue by TDA** [sasstools/sass-lint#765]
What version of Sass Lint are you using?
0.0.10
Please include any relevant parts of your configuration
Default config file, just installed with `npm i sasslint -g`

What did you do? Please include the actual source code causing the issue.
Ran `sasslint password.scss`.
Fails linting this:
```
.password-row {
  position: relative;
  &.input-row .password {
    html[dir=ltr] & {
      padding-right: 75px;
    }
    html[dir=rtl] & {
      padding-left: 75px;
    }
  }
}
```
What did you expect to happen?
Lint errors to appear

What actually happened? Please include any error messages given to you by Sass Lint.
`ParserException: Unexpected input token AMPERSAND at 3:3.`

If you're using a IDE plugin have you tried the CLI too?
This is from the CLI.

**Comment by TDA** [comment]
Ok, this was dumb. I am using sasslint and not sass-lint :| I should shut up.

**Comment by DanPurdy** [comment]
Didn't even realise this one existed! https://www.npmjs.com/package/sasslint

We've all done it before 👍  you should totally use sass-lint though ;)

**Comment by TDA** [comment]
@DanPurdy Switched over, and boy, has it been awesome! 💃 Great work guys!!
