### ISSUE TITLE
valid @each with & not working

### ISSUE THREAD

**Issue by alansouzati** [sasstools/sass-lint#770]
Using 1.8.2, happens both in cli and from IDE.

This block is a valid one and I get:  

> Please check validity of the block starting from line #91  Fatal

```
@each $status, $color in $brand-status-colors {
    &-#{$status} {
      .#{$grommet-namespace}status-icon__base {
        fill: $color;
      }
    }
}
```

If I remove the "-" it works normally:

```
@each $status, $color in $brand-status-colors {
    &#{$status} {
      .#{$grommet-namespace}status-icon__base {
        fill: $color;
      }
    }
}
```

Any pointers?

**Comment by DanPurdy** [comment]
It's an issue with the AST `gonzales-pe` I believe this PR will fix the issue for you https://github.com/tonyganch/gonzales-pe/pull/179 once it's merged and released.

**Comment by alansouzati** [comment]
Thanks for the follow up. For now I'm using the following work around, hope it helps folks facing similar issue:

```
@each $status, $color in $brand-status-colors {
  .#{$grommet-namespace}status-icon-#{$status} {
    .#{$grommet-namespace}status-icon__base {
      fill: $color;
    }
  }
}
```

Basically, I've moved the selector to be outside of the nested `&` scenario.

**Comment by DanPurdy** [comment]
@alansouzati this parses without error in sass-lint 1.9.0

**Comment by alansouzati** [comment]
thanks for the heads up @DanPurdy 👍
