### ISSUE TITLE
Where is my sass-lint.yml file

### ISSUE THREAD

**Issue by asaadmahmoodspin** [sasstools/sass-lint#785]
I would like to know where is my sass-lint.yml file. I have been using sass-lint in one of my other project and it works fine and I have a sass-lint.yml file there. However for my other projects I didn't create the sass-lint file but still the highlight works. Now I need to find out which file is it looking for when it's highlighting stuff so I can change it.

**Comment by asaadmahmoodspin** [comment]
Okay i found it out, it's in `/usr/local/Cellar/node/0.10.32/lib/node_modules/sass-lint/lib/config/sass-lint.yml`.

**Comment by DanPurdy** [comment]
@asaadmahmoodspin by default sass-lint uses the config file included within the package. You can then modify the settings in your own config or disable the `merge-default-rules` option to start from scratch. Check the config docs https://github.com/sasstools/sass-lint/tree/develop/docs/options and especially the `merge-default-rules` option https://github.com/sasstools/sass-lint/blob/develop/docs/options/merge-default-rules.md

**Comment by asaadmahmoodspin** [comment]
Does it use this one?
![screen shot 2016-07-13 at 3 13 54 pm](https://cloud.githubusercontent.com/assets/11034289/16799986/86e50862-490c-11e6-8e83-45c1b0255e45.png)

**Comment by DanPurdy** [comment]
Yes, that's the default config file.

**Comment by asaadmahmoodspin** [comment]
Okay cool, thanks!
