### ISSUE TITLE
Fix typos in no-vendor-prefixes rule documentation

### ISSUE THREAD

**Issue by basvandenberg** [sasstools/sass-lint#787]
There are some typos in the documentation of the [no-vendor-prefixes](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-vendor-prefixes.md) rule:

In the sub-section [Additional Identifiers](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-vendor-prefixes.md#additional-identifiers) the word `test` should be replaced with `khtml`.

In subsections [Additional Identifiers](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-vendor-prefixes.md#additional-identifiers) and [Excluded Identifiers](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/no-vendor-prefixes.md#excluded-identifiers) there is an example `yml` in which:

- The `no-vendor-prefix:` should be replaced with `no-vendor-prefixes:`.
- The key `'excluded-identifiers'` should be without quotes (`excluded-identifiers`).
- The corresponding values (`'khtml'`, `'webkit'`, `'moz'`) should also be without quotes.

**Comment by DanPurdy** [comment]
Thanks @basvandenberg do you have a PR waiting for this?

**Comment by basvandenberg** [comment]
Just created a new pull request.
