### ISSUE TITLE
sass-lint Bootstrap 3.3.6 fails on two mixin files

### ISSUE THREAD

**Issue by rernens** [sasstools/sass-lint#792]
What version of Sass Lint are you using?

I am using the angular-advanced-seed with scss support enabled meaning sass-lint is invoked through the gulp-sass-lint plugin.
Same error thrown when running the CLI interface.

Version installed of sass-lint is 1.8.2. Installed through npm 3.9.5

Please include any relevant parts of your configuration

no specific configuration file, using the default config.

What did you do? Please include the actual source code causing the issue.

fails in two mixin files of bootstrap 3.3.6

src/client/css/bootstrap/bootstrap/mixins/_grid-framework.scss
  37:1  error  Please check validity of the block starting from line #37  Fatal

@mixin calc-grid-column($index, $class, $type) {
  @if ($type == width) and ($index > 0) {                            <--- fails on this block
    .col-#{$class}-#{$index} {
      width: percentage(($index / $grid-columns));
    }
  }
  @if ($type == push) and ($index > 0) {
    .col-#{$class}-push-#{$index} {
      left: percentage(($index / $grid-columns));
    }
  }
  @if ($type == push) and ($index == 0) {
    .col-#{$class}-push-0 {
      left: auto;
    }
  }
  @if ($type == pull) and ($index > 0) {
    .col-#{$class}-pull-#{$index} {
      right: percentage(($index / $grid-columns));
    }
  }
  @if ($type == pull) and ($index == 0) {
    .col-#{$class}-pull-0 {
      right: auto;
    }
  }
  @if ($type == offset) {
    .col-#{$class}-offset-#{$index} {
      margin-left: percentage(($index / $grid-columns));
    }
  }
}

src/client/css/bootstrap/bootstrap/mixins/_forms.scss
  85:1  error  Please check validity of the block starting from line #85  Fatal

  textarea#{$parent}, select[multiple]#{$parent} {     <--- fails on select[multiple]#$parent
    height: auto;
  }

What did you expect to happen?

To properly compile ! Bootstrap-sass 3.3.6 is not known to have bugs in those mixins.

What actually happened? Please include any error messages given to you by Sass Lint.

see above

If you're using a IDE plugin have you tried the CLI too?

yes, same error thrown in the CLI

**Comment by DanPurdy** [comment]
Similar issue to #781 but it's an error in the AST we use Gonzales-pe. It'll be fixed in their latest release. See https://github.com/tonyganch/gonzales-pe/pull/179

**Comment by rernens** [comment]
@ DanPurdy thanks for the info. Any idea of an availability timeframe ?

**Comment by DanPurdy** [comment]
This code is now parsed correctly in sass-lint 1.9.0
