### ISSUE TITLE
Having sass-lint disable and enable linters using special inline comments

### ISSUE THREAD

**Issue by Olivia101** [sasstools/sass-lint#798]
Consider adding the ability to tell sass-lint disable/enable linters in a specific area of .scss file like it can be done with scss-lint as shown below:

// scss-lint:disable BorderZero
p {
  border: none; // No lint reported
}
// scss-lint:enable BorderZero

**Comment by DanPurdy** [comment]
Please try to search the existing issues before opening a new one. Thanks.

#70
#677

Closed as a duplicate
