### ISSUE TITLE
severity:warning - Feature Request

### ISSUE THREAD

**Issue by nathansmith** [sasstools/sass-lint#8]
If you're taking feature requests, I would love to be able to flag…

`severity: warning`

At a higher level than per linting rule, so that it doesn't throw `Exit status 1`, like the Ruby based scss-lint does.

**Comment by Snugug** [comment]
Throwing an error on failure is currently optional. so, done! (it'll work a lot like ESLint, which its modeled on)

**Comment by Snugug** [comment]
Throwing an error on failure is currently optional. so, done! (it'll work a lot like ESLint, which its modeled on)
