### ISSUE TITLE
Font-smoothing is non-standard

### ISSUE THREAD

**Issue by revoltpuppy** [sasstools/sass-lint#824]
**What version of Sass Lint are you using?**
grunt-sass-lint: ^0.2.0

**Please include any relevant parts of your configuration**

<pre><code>no-vendor-prefixes:
    - 2
    -
      additional-identifiers:
        - khtml
        - o
      ignore-non-standard: true</code></pre>

**What did you expect to happen?**
Expected the linter to ignore `-webkit-font-smoothing` and `-moz-osx-font-smoothing`.

According to MDN, [font-smooth (not font-smoothing, by the way) is non-standard](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth).

**What actually happened? Please include any error messages given to you by Sass Lint.**
Got error: “Vendor prefixes should not be used—no-vendor-prefixes” for both uses.

**Comment by DanPurdy** [comment]
@revoltpuppy thanks for this. Will look to get it fixed soon

**Comment by Nazin** [comment]
Any update on this issue?

**Comment by mjyoung** [comment]
Also would love for this to be fixed.

**Comment by alanshortis** [comment]
Another plus one for this. It's a bit of a blocker for me right now.

**Comment by DanPurdy** [comment]
Sorry about the wait, had to take a bit of an unschedule hiatus for a while there.

We will be releasing a V2 of sass-lint in the next couple of weeks to mainly drop support for old node versions but also to replace the vendor prefix rule. I've moved rules similar to stylelint's approach to this over to sass-lint but with added customisation options! Hopefully should remove the issues you've all been having.
