### ISSUE TITLE
no-mergeable-selectors can't handle media-queries with functions

### ISSUE THREAD

**Issue by thasmo** [sasstools/sass-lint#826]
When using a media-query with a function, like `@media(min-width: break('large'))` the `no-mergeable-selectors` rule has a false positive, because it's evaluating the rule to `@media(min-width: null)` for all `break` function calls and thus throws a warning for media-queries using different values in the `break` function.

This seems to be related to #703 which probably included a fix for variables but not for functions.

**Comment by DanPurdy** [comment]
Thanks for the issue @thasmo I'll look into it soon
