### ISSUE TITLE
Rule suggestion: Max file line count

### ISSUE THREAD

**Issue by DanPurdy** [sasstools/sass-lint#841]
Following on from #833 it would be good to port over TSLint's max-file-line-count rule too for those who wish to enforce a limit on the size/length of their files.

**Comment by chrismbarr** [comment]
The issue you linked to talks about adding a `max-line-length` rule, which woudl limit the number of character on each line of code.  This is different than the `max-file-line-count` rule, which limits how many lines of code can be in each file.  Both would be excellent additions though!

I actually wrote that `max-file-line-count` TSLint rule, so I'm all for it being added here! :smiley_cat: 

I'm unfamiliar with how the linting here works, but that TSLint rule is very simple.  I originally wrote it to just take the whole file text, split it on line breaks into an array, and just make sure the length of that array is less than the value in the configuration.  Later on I realized that their framework returns all the line start positions in an array, so I just used that and saved a step in the rule.  [See the relevant code here](https://github.com/palantir/tslint/blob/master/src/rules/maxFileLineCountRule.ts#L56-L63)

Either way works though, I don't know what the tools offer here, but as long as you can get the while file back as a string it would be very simple to implement.

**Comment by DanPurdy** [comment]
HI @chrismbarr awesome! The rule is actually already done in #842 if you'd like to take a look. Off the top of my head I followed the same pattern, just checking the line numbers of a node to check if it exceeded the limit. The reason that they haven't been merged in is I've caught a bug with our AST in the line length rule to do with .sass format with CRLF which has to be investigated.
