### ISSUE TITLE
Lint double semi colons

### ISSUE THREAD

**Issue by JordanDDisch** [sasstools/sass-lint#852]
Currently with trailing-semicolon on, double semi colons are not being linted.

e.g.
`.test {
  background: red;;
}`

As mentioned here in scss-lint as possible fix:
https://github.com/brigade/scss-lint/commit/0fc7ba821caf968505d3d130f60a94e832295803

Using gulp sass lint: "gulp-sass-lint": "^1.1.1"

**Comment by DanPurdy** [comment]
Thanks @JordanDDisch we'll look into it

**Comment by JordanDDisch** [comment]
I have a PR ready for this issue here #863
