### ISSUE TITLE
Add rule: declarations-before-nesting

### ISSUE THREAD

**Issue by onishiweb** [sasstools/sass-lint#865]
This rule should enforce that all declarations in a block should come before nesting

This:
```sass
.selector {
  property: value;

  .nested-selector {
    property: value;
  }
}
```

Not:
```sass
.selector {
  .nested-selector {
    property: value;
  }

  property: value;
}
```

Discussed in: https://github.com/Financial-Times/origami-build-tools/issues/268

**Comment by DanPurdy** [comment]
@onishiweb thanks for this, I'll hopefully find some time this weekend to go over this and hopefully pop it into our next release. Busy times at moment!
