### ISSUE TITLE
Convention strictbem produces unexpected linter warning

### ISSUE THREAD

**Issue by klickreflex** [sasstools/sass-lint#872]
**What version of Sass Lint are you using?** 
1.9.1

**Please include any relevant parts of your configuration**
OS X 10.11.6; Node v5.11.1; Sublime Text 3 Build 3114

**What did you do? Please include the actual source code causing the issue.**
Configured class-name-format to strictbem convention

    class-name-format:
     - 1
     -
       convention: strictbem

**What did you expect to happen?**
This should be valid bem:
`.main-menu__toggle_active`

**What actually happened? Please include any error messages given to you by Sass Lint.**
It is marked as Error: Class '.main-menu_toggle_active' should be written in BEM

**If you're using a IDE plugin have you tried the CLI too?**
Yes, same result:
`  64:2  warning  Class '.main-menu__toggle_active' should be written in BEM (Block Element Modifier) format  class-name-format`

It seems that one underscore is generally not permitted in class names , though according to the BEM spec that's what should be used to separate modifiers: (`.block__element_modifier`). 

Thanks for having a look,
Daniel

**Comment by DanPurdy** [comment]
Hi @klickreflex sorry for the late reply, been a busy summer! 

You're right, in strict bem there are two types of modifier, the boolean or the key value pair. Your example is technically a boolean modifier and should be perfectly valid (I use hyphenated bem myself so i had to double check this)

It looks as if just the regex selector is wrong. I'll update it in a PR now with some extra tests.

Thanks 👍
