### ISSUE TITLE
Support for eslint3

### ISSUE THREAD

**Issue by sminnee** [sasstools/sass-lint#875]
The latest release of sass-lint require `eslint ^2`. If you include eslint 3 in your project, it throws a warning that it's going to run on eslint 2, but it appears to function similarly when it uses eslint 3.

It would be good if there was an eslint 3 compatible version of sass-lint.

Looking at the code it seems as though only the formatters are used in this package. Could we simply mark the package as supporting eslint 2 or 3?

**Comment by alfaproject** [comment]
The reason it's using eslint 2 is because eslint 3 stopped supporting some versions of node that this project supports. I think the plan is to move to eslint 3 when those versions of node are no longer maintained, which will probably be soon anyway.

**Comment by DanPurdy** [comment]
There's no reason for us to move to eslint 3 at present and as @alfaproject rightly says it adds an overhead to our testing that we're not keen on right now. Once older node versions are out of LTS we'll start to adopt it I'm sure.
