### ISSUE TITLE
Exclude rules for specific lines/sections of scss code

### ISSUE THREAD

**Issue by laurakat** [sasstools/sass-lint#876]
Feature request: exclude rules for specific lines of code.

Currently it seems like entire files can be ignored, but you can't ignore only specific rules per file, or only for a small section of the code. 

scss-lint handles this but it doesn't seem to be available in sass-lint (https://github.com/brigade/scss-lint/#disabling-linters-via-source)

**Comment by DanPurdy** [comment]
Please see #70 and #677 for details.
