### ISSUE TITLE
use of !important in mixin throws fatal error

### ISSUE THREAD

**Issue by mmase** [sasstools/sass-lint#898]
``` scss
div {
  @include size(32px !important);
}
```

The above throws a fatal error. It's perfectly acceptable sass as of latest standard.

**Comment by DanPurdy** [comment]
This is a problem with the AST we use [Gonzales-pe](https://github.com/tonyganch/gonzales-pe) would you mind adding this issue there too please?

**Comment by DanPurdy** [comment]
FWIW -  it's down to the `!important` flag within the brackets

**Comment by mmase** [comment]
@DanPurdy sorry not sure what you mean by that :) can you clarify?

**Comment by DanPurdy** [comment]
Sorry,  nevermind it was late.

**Comment by bgriffith** [comment]
Just to note that this has been fixed in the parser https://github.com/tonyganch/gonzales-pe/pull/185 - just waiting for a release

**Comment by bgriffith** [comment]
This is fixed in the newly released version v1.11.0. Please let me know if you still have issues. Thanks!
