### ISSUE TITLE
Outdated concentric.yml

### ISSUE THREAD

**Issue by lucasjahn** [sasstools/sass-lint#921]
What version of Sass Lint are you using?
1.9.1

Please include any relevant parts of your configuration
I have the standard npm package using the concentric property ordering.

What did you do? Please include the actual source code causing the issue.
I updated the concentric.yml in /lib/config/property-sort-orders/ to match the in the comments highlighted list:

```
# Based on: https://github.com/brigade/scss-lint/blob/master/data/property-sort-orders/concentric.txt
```

you are now able to get a clean output if you want to use flex properties.

***solved in an open pullrequest***
#922

**Comment by DanPurdy** [comment]
closed in #922
