### ISSUE TITLE
strictbem helper v1.9.1 don't support boolean modifiers

### ISSUE THREAD

**Issue by mrchacon** [sasstools/sass-lint#928]
Documentation of rule `class-name-format` gives an example using strictbem case with boolean modifiers but regex in helper `helpers.isisStrictBEM` in v1.9.1 don't support this.

The regex, in the modifier part, explicitly expect the modifier to be in two parts (type:value). So boolean modifiers, that only need one part, can't be used.

The regex in v1.9.1 is:
((_[a-z0-9](\-?[a-z0-9]+)*)**{2}**).

I checked the develop branch and this has been fixed by using {0,2} instead.

When you're planning to release this change? This issue doesn't let me use BEM as expected.

**Comment by bgriffith** [comment]
Hey @mrchacon, we're looking at getting a release out in the next few days.

**Comment by DanPurdy** [comment]
I'll close this so we can just keep track of what's left.
