### ISSUE TITLE
ST3 can no longer handle errors in 1.10.0

### ISSUE THREAD

**Issue by Donaldini** [sasstools/sass-lint#934]
**What version of Sass Lint are you using?**
1.10.0

**Please include any relevant parts of your configuration**
Using Sublime Text 3 with: 

- _SublimeLinter 3.7.4_
- _SublimeLinter-contrib-sass-lint 1.0.4_

**What did you do? Please include the actual source code causing the issue.**
Wanted to update from sass-lint 1.8.2 to 1.10.0 so I removed sass-lint (globally and locally in current project), 
installed 1.10.0 (globally and locally) and afterwards my ST3 only showed the errors on the first line, without further detail.

Before the update (on 1.8.2)
![image](https://cloud.githubusercontent.com/assets/2185680/20056388/2d3ba312-a4e6-11e6-8601-09467a108ada.png)

in CLI: 
![image](https://cloud.githubusercontent.com/assets/2185680/20057428/bc7de710-a4eb-11e6-8cc5-70966c9248e7.png)

After the update (on 1.10.0)
![image](https://cloud.githubusercontent.com/assets/2185680/20057558/7b2d42f0-a4ec-11e6-93ef-8ba014057505.png)

In CLI:
![image](https://cloud.githubusercontent.com/assets/2185680/20057569/94489ff0-a4ec-11e6-9075-4aa27a7663e4.png)

**If you're using a IDE plugin have you tried the CLI too?**
Yes, see screenshots above.

I also tried the same thing on 1.9.1, but that still worked. It's only since 1.10.0 that it's acting up.

**Comment by DanPurdy** [comment]
Hi @Donaldini this is pretty worrying.. I'm not seeing this behaviour anywhere at the moment. Can you please post your config file for us in its entirety.

Thanks

**Comment by Donaldini** [comment]
Which config file do you need? sass-lint.yam?

**Comment by DanPurdy** [comment]
Yeah, if you're using one.

**Comment by Donaldini** [comment]
Here you go: [sass-lint.yml.zip](https://github.com/sasstools/sass-lint/files/575308/sass-lint.yml.zip)

**Comment by DanPurdy** [comment]
Hmm ok, I'll look into it, thanks.

**Comment by Donaldini** [comment]
I'm hoping it's something super easy 'cause I was really looking forward to that _disable rules_ feature :)

**Comment by DanPurdy** [comment]
Hey @Donaldini I think the error may be fixed in #937 We'll get a patch release out soon to prevent these un handled errors being thrown.

**Comment by DanPurdy** [comment]
Hi @Donaldini can you test it with 1.10.1 please and let me know if you still have problems.

**Comment by DanPurdy** [comment]
I've tested this in sublime myself. Can't replicate it so closing. Happy to reopen if we hear back that it's not fixed.

**Comment by Donaldini** [comment]
Tested it with 1.10.1 and the problem seems to be fixed! Thanks

**Comment by DanPurdy** [comment]
Awesome, sorry to cause you the trouble in the first place!
