### ISSUE TITLE
release broken on 0.12 without major version bump

### ISSUE THREAD

**Issue by huerlisi** [sasstools/sass-lint#946]
First off: thanks for this wonderful package, we're using it with great success!

We're still using Node version 0.12 in some environments. These projects are now failing due to incompatibility of newer `eslint` versions.

`eslint` properly bumped the package version in a major release when requiring a newer node version. `sass-lint` did bump the dependency on  `eslint` in 31d26aa. This did change the dependency version from `^2.7.0` to `^3.9.1` and does therefore allow breaking changes in the `eslint` dependency.

As said, this dependency upgrade broke `sass-lint` on node 0.12. So it is a breaking change for `sass-lint`. Unfortunately this change was included in a patch release.

I understand that you made the decission to drop support for 0.10 and 0.12 in #896. But I think actually breaking this support is something that according to semver is a breaking change and therefore should be only done in a major release.

**Comment by alfaproject** [comment]
eslint should be a dev dependency though, and this wouldn't have been an issue in the first place?

**Comment by DanPurdy** [comment]
We depend on it for hte formatters currently as we dont have our own.

**Comment by DanPurdy** [comment]
Either way @huerlisi 1.10.2 is out now with Eslint pegged back. I'll release an update to all the tools too.

**Comment by huerlisi** [comment]
Wow, that's a great relieve for us! Marvelous work!

(and it gave us a much needed push to migrate away from those old platforms)
