### ISSUE TITLE
Empty lines with whitespace not recognized by the empty-line-between-blocks rule

### ISSUE THREAD

**Issue by FiniteLooper** [sasstools/sass-lint#965]
Using Sass Lint version `1.3.2`

These causes a violation of the `empty-line-between-blocks` rule due to the whitespace characters on the empty line between blocks.  
![image](https://cloud.githubusercontent.com/assets/463685/20524778/193e4d10-b08a-11e6-805e-788f950648a3.png)

However, when the line is actually blank, no violations are reported.
![image](https://cloud.githubusercontent.com/assets/463685/20524757/0104ccc4-b08a-11e6-8afd-ac90165971b9.png)

IMO, all of these should be valid.  There **is an empty line between those two blocks** and it seems silly to require no whitespace on the empty line between blocks.  The line is visually blank, which I believe is the intended purpose of this rule.

**Comment by DanPurdy** [comment]
I'll need to check how we're looking at the AST for this one. Off the top of my head the newline character and the whitespace on the following line will be considered a space node so it could be that we're just checking for block termination rather than content on the line.
