### ISSUE TITLE
sass-lint.yml not found.

### ISSUE THREAD

**Issue by cj** [sasstools/sass-lint#973]
I'm running version `1.10.2`, I have a `.sass-lint.yml` in the root of my project.  When I run `sass-lint src/theme/button.scss`` I get the following error:

```viml
cj at cj-mac in ~/Sync/apps/acd/m on mat!
± sass-lint src/theme/button.scss
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/cj/Sync/apps/acd/m/node_modules/sass-lint/lib/config/sass-lint.yml'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.loadDefaults (/Users/cj/Sync/apps/acd/m/node_modules/sass-lint/lib/config-helpers.js:13:27)
    at module.exports (/Users/cj/Sync/apps/acd/m/node_modules/sass-lint/lib/config.js:80:26)
    at Function.sassLint.getConfig (/Users/cj/Sync/apps/acd/m/node_modules/sass-lint/index.js:31:10)
    at Object.<anonymous> (/Users/cj/Sync/apps/acd/m/node_modules/sass-lint/bin/sass-lint.js:76:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

```
± nvim --version
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161202-25906-1xcct63/neovim-0.1.7/build/config -I/tmp/neovim-20161202-25906-1xcct63/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I/tmp/neovim-20161202-25906-1xcct63/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20161202-25906-1xcct63/neovim-0.1.7/build/include
Compiled by cj@MacBook-Pro.tx.rr.com

Optional features included (+) or not (-): +acl   +iconv    -jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```

**Comment by DanPurdy** [comment]
This is the default config file in sass-lint that it can't find for some reason. I'm not sure why you're getting this. Try installing sass-lint again or check in that directory that it mentions to see if the .sass-lint.yml file is missing.

**Comment by cj** [comment]
@DanPurdy I'm getting the same message.  The only think I can think of is this was installed with yarn doing `yarn add --dev sass-lint`.  I've had some issues with some npm packages that need to be installed globally, where doing `yarn global add` they didn't work quite right and I had to resort to `npm install -g`.  Maybe it could be something similar....

**Comment by DanPurdy** [comment]
If you could let us know if that fixes your problem that would be great.

**Comment by damonsmith** [comment]
We just switched over from npm to yarn and I had the same problem - yarn doesn't seem to do a full install of sass-lint so /node_modules/sass-lint/lib/config/sass-lint.yml is missing.

Just doing an npm install sass-lint fixes it. (no need to do a install -g)

Is there some extra post install script that puts the sass-lint file in place?

If I then delete sass-lint from node_modules and run yarn add sass-lint I get the same error. Yarn is creating the sass-lint module but inside it there is a lib/config with only an empty directory called property-sort-orders and nothing else.

.. just going to have a look in this repo to see what installs the contents of that folder.

**Comment by DanPurdy** [comment]
@damonsmith there is no postinstall script, these files are part of the repository and the default install. If Yarn isn't downloading them then all I can think is that there's a bug in yarn. I would maybe post an issue there?

**Comment by damonsmith** [comment]
yes I see they're just sitting there straight in the repo. Definitely a yarn issue, just wondering what exactly. It turns out I'm the only one on my team that has the problem. We all have macOS, same node version setup with nvm, we all deleted node_modules and ran yarn again and only I got the problem.

Totally strange that it's me and it happens to be this package that I get it with too. I suspect yarn is doing some sort of performance optimization of the files it thinks it needs to download but I'll raise it with them and read up on getting some more verbose logging of yarn when it runs.

**Comment by DanPurdy** [comment]
Had you done a Yarn clean? Wondering if that has wiped the files out? Maybe delete the yarn.lock and yarn clean files and try again?

**Comment by damonsmith** [comment]
Ah ok thanks, I'll give that a try tomorrow. Funny thing is we just converted to yarn and it happened on the very first run of yarn on my system. I was off for a day though when we converted to yarn, maybe everyone else just sacrificed the right goats while I was away.

Also I'll raise a ticket with yarn for it.

**Comment by damonsmith** [comment]
Yes running a `yarn cache clean` and then `yarn` fixed the problem. 

Before it fixed the problem though, I checked the cached version in ~/Library/Caches/Yarn/npm-sass-lint-1.10.2-<hash> and it did have all the files. 

Running yarn in verbose lists all the files that it copies from the cache folder and it lists each one that it copied but it didn't copy the sass-lint.yml file and the logs don't explain why either. Strange.

**Comment by fjoesne** [comment]
I had a similar issue. .yarnclean adds *.yml and therefore it will be removed without any notice at package install /  #upgrade. 

#2259

**Comment by DanPurdy** [comment]
We can think about it for the future but we're not gonna change sasslint right now purely because yarn chooses to do that. I guess once we add json config's we can move it over but i just don't have the time right now. Until then it remains an issue with yarn..

**Comment by dennis-best** [comment]
In case someone finds themselves here with the yarn issue: "It's a feature not a bug"

Add `!sass-lint.yml` to your project's .yarnclean file and it will not get removed.
