### ISSUE TITLE
Space After Colons doesn't work inside of arguments

### ISSUE THREAD

**Issue by Snugug** [sasstools/sass-lint#98]
For instance, inside of Media Query arguments:

https://github.com/bgriffith/sass-lint/commit/2ceb329be1e014ddf7c71508eabf37d59a223e07#diff-9749c71a6762edb9480fb15c79950231R23

**Comment by bgriffith** [comment]
Had a quick look and the issue is that properties inside a media query aren't classified as a `propertyDelimiter` so he doesn't include them in the loop.

**Comment by DanPurdy** [comment]
What are they classed as?

**Comment by bgriffith** [comment]
Just operators

```
{
                      "type": "operator",
                      "content": ":",
                      "syntax": "scss",
                      "start": {
                        "line": 2,
                        "column": 20
                      },
                      "end": {
                        "line": 2,
                        "column": 20
                      }
                    }
```

**Comment by bgriffith** [comment]
Shouldn't the title of this be 'Space after colon..? instead of parens?

**Comment by Snugug** [comment]
Yah… probably…
