### ISSUE TITLE
[sass|scss] Sass-lint breaks after map is given

### ISSUE THREAD

**Issue by VaclovasV** [sasstools/sass-lint#982]
What version of Sass Lint are you using? 1.10.2

What did you do? Please include the actual source code causing the issue.
`$layout-global-config: (
    buttonPrimary: (
        disabled: $color-blue-gray
    ),
    height: (
        topNavigations: 140px
    ),
    font: (
        default: $base-font-family,
        size: $base-font-size
    ),
    placeholder:(
        color: $color-gray-dark,
    ),
    header: (
        height: 64px,
        bg: $color-red
    ),
    border: (
        default: 1px solid $color-gray,
        color: $color-gray,
        focused: $color-blue,
        radius: 3px
    ),
    checkbox: (
        labelColor: $color-gray-dark,
        checkedBg: $color-blue,
        checkedBorder: $color-blue
    ),
    error: (
        color: $color-red-light
    ),
    tooltip: (
        bg: #fbfbfb
    ),
    shadow: (
        default: 0 4px 6px 2px $color-shadow
    ),
    bodyPreloader: (
        zIndex: 99999 !important
    ),
    notification: (
        color: $color-gray-dark
    ),
    progress: (
        height: 75px,
        link-height: 28px,
        shadow: 0 1px 6px 6px $color-shadow-header
    ),
    select: (
        shadow: $select-shadow
    ),
    label: (
        color: $color-label-grey
    )
);`

What actually happened? Please include any error messages given to you by Sass Lint.
public\scss\base\_config.scss
  67:1  error  Please check validity of the block starting from line #67  Fatal

**Comment by DanPurdy** [comment]
@VaclovasV The issue here is with the AST we use, [Gonzales-pe](https://github.com/tonyganch/gonzales-pe) you can file an issue there about this.

**Comment by bgriffith** [comment]
Note to self - appears to be down to the `!important`

**Comment by bgriffith** [comment]
The parser bug has been fixed as of `v1.11.1`
