### ISSUE TITLE
Add to package.json whitelist files

### ISSUE THREAD

**Issue by ahiipsa** [sasstools/sass-lint#986]
Hi, 
sass-lint installation include unnecessary files (tests, .travis.yml and other). It increases the size and installation time.

npm has directive `files` in `package.json` [doc](https://docs.npmjs.com/files/package.json#files)

I created [example](https://github.com/ahiipsa/sass-lint/blob/files/package.json#L15-L21)

You may test it:
```
npm install git@github.com:ahiipsa/sass-lint.git#files
```

What do you think about this?

**Comment by DanPurdy** [comment]
Released in 1.12.0
